---
settings:
  name: Astra Control Service
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  filter:
    label: クラウドプロバイダ
    default: すべてのクラウドプロバイダ
    options:
    - name: Amazon Web Services の
      alias: Amazon Web Services の
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  rss_page: release-notes/whats-new.html
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Astra Control Service のドキュメント
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: learn
  - section: use
  - title: Astra Control REST API で自動化
    url: "/automation.html"
  - section: support
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: すべてのAstraドキュメント
