---
sidebar: sidebar 
permalink: learn/azure-storage.html 
keywords: service level, cvs, cvs-performance, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance 
summary: Astra Control Service は、 Azure Kubernetes Service （ AKS ）クラスタのストレージバックエンドとして Azure NetApp Files を使用します。ストレージクラスと永続的ボリュームのサイズを選択することがパフォーマンス目標の達成にどのように役立つかを理解しておく必要があります。 
---
= AKS クラスタのストレージクラスと PV サイズ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


[role="lead"]
Astra Control Serviceは、Azure Kubernetes Service（AKS）クラスタのストレージバックエンドとして、Azure NetApp Files 、Azureで管理されるディスク、またはNetApp Cloud Volumes ONTAP をサポートします。



== Azure NetApp Files の特長

Astra Control Service は、 Azure Kubernetes Service （ AKS ）クラスタのストレージバックエンドとして Azure NetApp Files をサポートします。ストレージクラスと永続的ボリュームのサイズを選択することがパフォーマンス目標の達成にどのように役立つかを理解しておく必要があります。



=== サービスレベルとストレージクラス

Azure NetApp Files は、 Ultra ストレージ、 Premium ストレージ、 Standard ストレージの 3 つのサービスレベルをサポートします。これらのサービスレベルは、それぞれパフォーマンスのニーズに応じて次のように設計されています。

ウルトラストレージ:: 1TiB あたり最大 128 MiB/ 秒のスループットを提供します。
Premium Storage の場合:: 1TiB あたり最大 64 MiB/ 秒のスループットを提供します。
標準的なストレージ:: 1TiB あたり最大 16 MiB/ 秒のスループットを提供します。


これらのサービスレベルは容量プールの属性です。Kubernetes クラスタで使用するサービスレベルごとに容量プールを設定する必要があります。 link:../get-started/set-up-microsoft-azure-with-anf.html["容量プールの設定方法について説明します"]。

Astra Control Service は、永続ボリュームのストレージクラスとしてこれらのサービスレベルを使用します。Kubernetes クラスタを Astra Control Service に追加する場合、デフォルトのストレージクラスとして Ultra 、 Premium 、または Standard のいずれかを選択するように求められます。ストレージクラスの名前は、 _NetApp-anf-perf-ultra 、 _NetApp-anf-pPremium_ 、および _NetApp-anf-pperf-standard_ です。

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels["これらのサービスレベルの詳細については、 Azure NetApp Files のドキュメントを参照してください"^]。



=== 永続的なボリュームのサイズとパフォーマンス

前述したように、各サービスレベルのスループットは、プロビジョニング済み容量の 1TiB あたりのスループットです。つまり、ボリュームのサイズが大きいほどパフォーマンスが向上します。したがって、ボリュームのプロビジョニング時には、容量とパフォーマンスの両方のニーズを考慮する必要があります。



=== 最小ボリュームサイズ

Astra Control Service は、 PVC でボリュームサイズの縮小が要求されても、 100GiB 以上の最小ボリュームサイズを使用して永続的ボリュームをプロビジョニングします。たとえば、 Helm チャートの PVC で 6GiB が要求された場合、 Astra Control Service は 100GiB のボリュームを自動的にプロビジョニングします。



=== アプリケーションのバックアップ

Azure NetApp Files ストレージにあるアプリケーションをバックアップすると、容量プールが自動的に一時的に拡張されます。バックアップの完了後、Astra Control Serviceによって容量プールが以前のサイズに縮小されます。Azureサブスクリプションによっては、このような場合にストレージ料金が発生することがあります。容量プールのサイズ変更イベントの履歴は、*[アクティビティ]*ページのイベントログで確認できます。

サイズ変更処理中に容量プールがAzureサブスクリプションで許可されている最大サイズを超えると、バックアップ処理は失敗し、Azure APIから警告がトリガーされます。



== Azure で管理されるディスク

Astra Control Serviceでは、Container Storage Interface（CSI）ドライバを使用して、Azure Managed Disksをストレージバックエンドとしてインターフェイスできます。このサービスは、 Azure で管理されるブロックレベルのストレージを提供します。

https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Azure で管理されるディスクに関する詳細はこちらをご覧ください"^]。



== NetApp Cloud Volumes ONTAP の略

パフォーマンスに関する推奨事項など、NetApp Cloud Volumes ONTAP の設定に関する具体的な情報については、を参照してください https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["NetApp Cloud Volumes ONTAP のドキュメント"^]。
