---
sidebar: sidebar 
permalink: learn/data-protection.html 
keywords: backup, back up, backup apps, back up apps, snapshots, snapshot an app, take a snapshot, take a backup, view backups, view snapshots, set policy, set schedule, schedule backups, schedule snapshots, protect data 
summary: Astra Control Serviceで利用可能なデータ保護の種類と、それらを使用してアプリケーションを保護する最適な方法について説明します。 
---
= データ保護
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


[role="lead"]
Astra Control Serviceで利用可能なデータ保護の種類と、それらを使用してアプリケーションを保護する最適な方法について説明します。



== Snapshot 、バックアップ、保護のポリシー

Snapshotとバックアップのどちらも、次のタイプのデータを保護します。

* アプリケーション自体
* アプリケーションに関連付けられている永続的データボリューム
* アプリケーションに属するリソースアーティファクト


a_snapshot_は 、アプリケーションと同じプロビジョニングボリュームに格納されるアプリケーションのポイントインタイムコピーです。通常は高速です。ローカル Snapshot を使用して、アプリケーションを以前の時点にリストアできます。スナップショットは高速クローンに便利です。スナップショットには、構成ファイルを含む、アプリケーションのすべての Kubernetes オブジェクトが含まれます。スナップショットは、同じクラスタ内でアプリケーションをクローニングまたはリストアする場合に便利です。

_backup_はSnapshotに基づいています。外部のオブジェクトストアに格納されるため、ローカルSnapshotに比べて取得に時間がかかることがあります。アプリケーションのバックアップを同じクラスタにリストアすることも、バックアップを別のクラスタにリストアして移行することもできます。バックアップの保持期間を延長することもできます。バックアップは外部のオブジェクトストアに格納されるため、サーバで障害が発生したりデータが失われたりした場合に備えて、 Snapshot よりも優れた保護機能を提供できます。

a_protection policy__ は、アプリケーション用に定義したスケジュールに従って、スナップショット、バックアップ、またはその両方を自動的に作成することで、アプリケーションを保護する方法です。また、保護ポリシーでは、スケジュールで保持するSnapshotとバックアップの数を選択したり、さまざまなスケジュールレベルを設定したりすることもできます。保護ポリシーを使用してバックアップとスナップショットを自動化することは、組織のニーズやSLA（Service Level Agreement）の要件に応じて各アプリケーションを確実に保護するための最良の方法です。


CAUTION: _ 最新のバックアップがあるまで、完全に保護することはできません _ 。これは、永続ボリュームから離れたオブジェクトストアにバックアップが格納されるために重要です。障害または事故によってクラスタとその永続的ストレージが消去された場合は、バックアップをリカバリする必要があります。Snapshot を使用してリカバリすることはできません。


NOTE: スナップショットまたはバックアップを実行しても、操作が失敗し、「The resource was n't created because of an internal server問題 」というエラーが表示された場合は、使用しているストレージバックエンドに正しいドライバがインストールされていることを確認します。ストレージバックエンドの中には、Container Storage Interface（CSI）ドライバを必要とするものと、外部スナップショットコントローラを必要とするものがあります。



== クローン

a_clone_は、アプリケーション、その設定、および永続データボリュームの完全な複製です。クローンは、同じ Kubernetes クラスタまたは別のクラスタに手動で作成できます。アプリケーションとストレージを Kubernetes クラスタ間で移動する必要がある場合は、アプリケーションをクローニングすると便利です。
