---
sidebar: sidebar 
permalink: learn/user-roles-namespaces.html 
keywords: users, roles, user roles, namespace, namespaces, account, accounts, permissions, restriction, restrict, constraint 
summary: Astra Controlで使用可能なデータ保護の種類と、それらを使用してアプリケーションを保護する最適な方法について説明します。 
---
= ユーザロールとネームスペース
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


[role="lead"]
Astra Control のユーザロールとネームスペースについて説明し、それらを使用して組織内のリソースへのアクセスを制御する方法を説明します。



== ユーザロール

ロールを使用して、ユーザが Astra Control のリソースまたは機能にアクセスできるように制御できます。Astra Control のユーザロールは次のとおりです。

* * 所有者 * には管理者権限があり、アカウントを削除できます。
* * Admin * にはメンバー権限があり、他のユーザーを招待できます。
* メンバー * は、アプリとクラスターを完全に管理できます。
* * Viewer * はリソースを表示できます。


メンバーまたはビューアユーザーに制約を追加して、ユーザーを 1 つ以上に制限できます <<ネームスペース>>。



== ネームスペース

ネームスペースは、 Astra Control によって管理されるクラスタ内の特定のリソースに割り当てることができるスコープです。Astra Control では、 Astra Control にクラスタを追加すると、クラスタのネームスペースが検出されます。検出されたネームスペースは、ユーザに制約として割り当てることができます。そのリソースを使用できるのは、そのネームスペースにアクセスできるメンバーだけです。名前空間を使用すると、組織に適したパラダイム（たとえば、会社内の物理的なリージョンや部門）を使用して、リソースへのアクセスを制御できます。ユーザに制約を追加する場合は、そのユーザにすべてのネームスペースへのアクセス権を設定するか、特定のネームスペースのセットのみを設定できます。ネームスペースラベルを使用して、ネームスペースの制約を割り当てることもできます。



== 詳細については、こちらをご覧ください

* link:../use/manage-roles.html["ロールの管理"]

