---
sidebar: sidebar 
permalink: learn/validated-vs-standard.html 
keywords: supported apps 
summary: Astra Control 、 Validated 、 Standard の 2 種類のアプリケーションを利用できます。これら 2 つのカテゴリの違いと、プロジェクトと戦略に与える可能性のある影響について説明します。 
---
= 検証済みのアプリケーションと標準のアプリケーションの比較
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


Astra Control には、検証済みと標準の 2 種類のアプリケーションが用意されています。これら 2 つのカテゴリの違いと、プロジェクトと戦略に与える可能性のある影響について説明します。


NOTE: この 2 つのカテゴリは、「サポート対象」と「サポート対象外」と考える傾向があります。 しかし、ここでは、 Astra Control の「サポートされていない」アプリケーションなどのものはありません。Astra Control には任意のアプリケーションを追加できますが、検証済みのアプリケーションは、 Astra Control ワークフローを中心に構築された、標準のアプリケーションよりも多くのインフラを備えています。



== 検証済みのアプリケーション

Astra Control の検証済みアプリケーションには、次のものがあります。

* MySQL 8.0.25
* MariaDB 10.5.9
* PostgreSQL 11.12
* Jenkins 2.277.4 LTS および 2.289.1 LTS


検証済みアプリケーションのリストは、 Astra Control が認識するアプリケーションを表します。Astra Control チームは、これらのアプリケーションを分析して確認し、完全なテストでリストアできることを確認しました。Astra Control は、カスタムワークフローを実行して、アプリケーションレベルでのスナップショットとバックアップの整合性を確保します。

アプリケーションが検証された場合、 Astra Control チームは、アプリケーションと整合性のあるスナップショットを取得するためにスナップショットを取得する前に、アプリケーションを休止するための手順を特定して実装しました。たとえば、 Astra Control が PostgreSQL データベースのバックアップを作成する場合、最初にデータベースを休止します。バックアップが完了すると、 Astra Control はデータベースを通常の動作に復元します。

Astra Control で使用するアプリケーションの種類に関係なく、必ず自分でバックアップとリストアのワークフローをテストして、ディザスタリカバリの要件を満たすようにしてください。



== 標準アプリ

カスタムプログラムを含むその他のアプリケーションは、標準アプリケーションと見なされます。Astra Control を使用して、標準アプリケーションを追加および管理できます。また、標準アプリケーションの基本的な crash-consistent Snapshot とバックアップを作成することもできます。ただし、これらは、アプリケーションを元の状態に戻すために完全にテストされていません。


TIP: Astra Control 自体は標準のアプリケーションではなく、「システムアプリケーション」です。 Astra Control 自体は、管理用にデフォルトでは表示されません。Astra Control 自体は管理しないでください。
