---
sidebar: sidebar 
permalink: learn/validated-vs-standard.html 
keywords: supported apps 
summary: Astra Control 、 Validated 、 Standard の 2 種類のアプリケーションを利用できます。これら 2 つのカテゴリの違いと、プロジェクトと戦略に与える可能性のある影響について説明します。 
---
= 検証済みのアプリケーションと標準のアプリケーションの比較
:hardbreaks:
:icons: font
:imagesdir: ../media/learn/


Astra Control には、 Validated と Standard の 2 種類のアプリケーションがあります。これら 2 つのカテゴリの違いと、プロジェクトと戦略に与える可能性のある影響について説明します。


NOTE: この 2 つのカテゴリは、「サポート対象」と「サポート対象外」と考える傾向があります。 しかし、ここでは、 Astra Control の「サポートされていない」アプリケーションなどのものはありません。Astra Control には任意のアプリケーションを追加できますが、検証済みのアプリケーションは、 Astra Control ワークフローを中心に構築された、標準のアプリケーションよりも多くのインフラを備えています。



== 検証済みのアプリケーション

Astra Control の検証済みアプリケーションには、次のものがあります。

* MySQL 0.3.22
* MariaDB 14.14
* PostgreSQL 11.7
* Jenkins 2.249.1 LTS


検証済みアプリケーションの短いリストは、 Astra Control が認識するアプリケーションを表しています。Astra Control QA チームは、これらのアプリケーションを分析して確認し、完全なテストでリストアできることを確認しました。

また、 Astra Control Development チームが検証済みのアプリケーションもチェックしており、データの安全性と一貫性を確保するためのカスタムワークフローを作成しています。たとえば、 Astra Control が PostgreSQL データベースのバックアップを作成する場合、最初にデータベースを休止します。バックアップが完了すると、 Astra Control はデータベースを通常の動作に復元します。

Astra Control で使用するアプリケーションの種類に関係なく、必ず自分でバックアップとリストアのワークフローをテストして、ディザスタリカバリの要件を満たすようにしてください。

今後検証するアプリをお知らせします。 https://astra.netapp.io/support["サポートページのフィードバック E メールアドレスからお問い合わせください。"]



== 標準アプリ

カスタムプログラムを含むその他のアプリは、標準アプリと見なされます。Astra Control を使用して、標準アプリケーションを追加および管理できます。また、標準アプリケーションの crash-consistent Snapshot とバックアップの基本的な作成も可能です。ただし、これらのアプリケーションを元の状態に戻すための QA テストは実施されていません。
