---
sidebar: sidebar 
permalink: solutions/mysql-deploy-from-helm-chart.html 
keywords: helm, mysql, helm chart, deploy mysql, astra, astra control, kubernetes 
summary: 標準の安定したグラフから MySQL を導入する方法を説明します。Kubernetes クラスタに MySQL を導入したら、 Astra Control を使用してアプリケーションを管理できます。 
---
= Helm チャートから MySQL を導入します
:hardbreaks:
:icons: font
:imagesdir: ../media/


から MySQL を導入する方法について説明します https://github.com/helm/charts/tree/master/stable/mysql["標準安定チャート"^]。Kubernetes クラスタに MySQL を導入したら、 Astra Control を使用してアプリケーションを管理できます。

MySQL は Astra Control の検証済みアプリケーションです。 link:../learn/validated-vs-standard.html["検証済みアプリケーションと標準アプリケーションの違いをご確認ください"]。

以下の手順は、 Astra Control Service と Astra Control Center の両方に適用されます。



== 要件

* Astra Control に追加されたクラスタ。
+

NOTE: Astra Control Center では、最初にクラスタを Astra Control Center に追加するか、最初にアプリケーションを追加できます。

* クラスタの適切な kubeconfig を使用してローカルマシンにインストールされている Helm （バージョン 3.2+ ）および Kubectl のバージョンを更新しました




== MySQL をインストール

このプロセスに関する 2 つの重要な注意事項：

* アプリケーションは、クラスタを Astra Control Service に追加したあとに、以前には導入しないでください。Astra Control Center は、 Astra Control Center にクラスタを追加する前後のアプリケーションを受け入れます。
* Helm チャートをデフォルト以外の名前空間に展開することをお勧めします。


.手順
. Bitnami チャート repo を追加します。
+
[listing]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
----
. 次のコマンドを使用して MySQL を導入します。
+
[listing]
----
Helm install <name> --namespace <namespace> --create-namespace -–set persistence.storageClass=<storage_class>
----
+

NOTE: ボリュームサイズを変更する場合は、 Kibibyte （ KI ）、 Meibyte （ MI ）、または Gibyte （ Gi ）単位を使用します。

+
ストレージクラスを定義する必要があるのは、次の場合のみです。

+
** Astra Control サービスを使用していて、デフォルトのストレージクラスを使用しない場合。
** Astra Control Center を使用していて、まだ Astra Control Center にクラスタをインポートしていない。あるいは、クラスタをインポートしたあとに、デフォルトのストレージクラスを使用する必要がなくなった場合。




これにより、次の処理が行われます。

* ネームスペースを作成します。
* ネームスペースに MySQL を導入します。


ポッドがオンラインになったら、 Astra Control を使用してアプリケーションを管理できます。Astra Control を使用すると、名前を付けてアプリケーションを管理したり、ネームスペースレベルでアプリケーションを管理したり、 Helm ラベルを使用したりできます。
