---
sidebar: sidebar 
permalink: use-acp/acp-snap-restore.html 
keywords: snapshot restore, snapshot, astra control provisioner, TridentActionSnapshotRestore, 
summary: 'Astra Control Provisionerを使用すると、Snapshotからボリュームをインプレースですばやくリストアできます。 `TridentActionSnapshotRestore` （TASR）CR。このCRはKubernetesの必須アクションとして機能し、処理の完了後も維持されません。' 
---
= Snapshotを使用したボリュームデータのリカバリ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control Provisionerを使用すると、Snapshotからボリュームをインプレースですばやくリストアできます。 `TridentActionSnapshotRestore` （TASR）CR。このCRはKubernetesの必須アクションとして機能し、処理の完了後も維持されません。

Astra Control Provisionerは、上でのSnapshotのリストアをサポートします。 `ontap-san`、 `ontap-san-economy`、 `ontap-nas`、 `ontap-nas-flexgroup`、 `azure-netapp-files`、 `gcp-cvs`および `solidfire-san` ドライバ。

.作業を開始する前に
バインドされたPVCと使用可能なボリュームSnapshotが必要です。

* PVCステータスがバインドされていることを確認します。
+
[listing]
----
kubectl get pvc
----
* ボリュームSnapshotを使用する準備が完了していることを確認します。
+
[listing]
----
kubectl get vs
----


.手順
. TASR CRを作成します。次に、PVC用のCRを作成する例を示します。 `pvc1` ボリュームSnapshot `pvc1-snapshot`。
+
[listing]
----
cat tasr-pvc1-snapshot.yaml

apiVersion: v1
kind: TridentActionSnapshotRestore
metadata:
  name: this-doesnt-matter
  namespace: trident
spec:
  pvcName: pvc1
  volumeSnapshotName: pvc1-snapshot
----
. スナップショットからリストアするにはCRを適用します。この例では、Snapshotからリストアします。 `pvc1`。
+
[listing]
----
kubectl create -f tasr-pvc1-snapshot.yaml

tridentactionsnapshotrestore.trident.netapp.io/this-doesnt-matter created
----


.結果
Astra Control ProvisionerがSnapshotからデータをリストアします。Snapshotのリストアステータスを確認できます。

[listing]
----
kubectl get tasr -o yaml

apiVersion: v1
items:
- apiVersion: trident.netapp.io/v1
  kind: TridentActionSnapshotRestore
  metadata:
    creationTimestamp: "2023-04-14T00:20:33Z"
    generation: 3
    name: this-doesnt-matter
    namespace: trident
    resourceVersion: "3453847"
    uid: <uid>
  spec:
    pvcName: pvc1
    volumeSnapshotName: pvc1-snapshot
  status:
    startTime: "2023-04-14T00:20:34Z"
    completionTime: "2023-04-14T00:20:37Z"
    state: Succeeded
kind: List
metadata:
  resourceVersion: ""
----
[NOTE]
====
* ほとんどの場合、障害が発生したときにAstra Control Provisionerで処理が自動的に再試行されません。この操作を再度実行する必要があります。
* 管理者アクセス権を持たないKubernetesユーザは、アプリケーションネームスペースにTASR CRを作成するために、管理者から権限を付与されなければならない場合があります。


====