---
sidebar: sidebar 
permalink: use/clone-apps.html 
keywords: clone app, clone storage, clone persistent storage, clone data, move workload, clone data, migrate data, data migration, move storage, move application, move data 
summary: 既存のアプリケーションをクローニングして、同じ Kubernetes クラスタまたは別のクラスタに重複するアプリケーションを作成する。Kubernetes クラスタ間でアプリケーションとストレージを移動する必要がある場合は、クローニングが役立ちます。たとえば、 CI CD パイプラインや Kubernetes ネームスペース間でワークロードを移動できます。 
---
= アプリケーションのクローン作成と移行
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
既存のアプリケーションをクローニングして、同じKubernetesクラスタまたは別のクラスタに重複するアプリケーションを作成できます。Astra Control でアプリケーションをクローニングすると、アプリケーション構成と永続的ストレージのクローンが作成されます。

Kubernetes クラスタ間でアプリケーションとストレージを移動する必要がある場合は、クローニングが役立ちます。たとえば、 CI / CD パイプラインや Kubernetes ネームスペース間でワークロードを移動できます。

.必要なもの
* アプリケーションを別のクラスタにクローニングするには、ソースクラスタとデスティネーションクラスタを含むクラウドインスタンス（同じでない場合）にデフォルトのバケットを用意する必要があります。クラウドインスタンスごとにデフォルトのバケットを割り当てる必要があります。
* クローン処理中に、IngressClassリソースまたはwebhookを必要とするアプリケーションが正常に機能するためには、これらのリソースがデスティネーションクラスタですでに定義されていない必要があります。


.クローンの制限事項
* *明示的ストレージクラス*：ストレージクラスを明示的に設定したアプリケーションを導入し、そのアプリケーションのクローンを作成する必要がある場合、ターゲットクラスタには元 々 指定されたストレージクラスが必要です。ストレージクラスを明示的に設定したアプリケーションを、同じストレージクラスを含まないクラスタにクローニングすると、失敗します。
* *クローンとユーザーの制約*：名前空間の名前/ IDまたは名前空間のラベルによって名前空間の制約を持つメンバーユーザーは、同じクラスタ上の新しい名前空間、または組織のアカウント内の他の任意のクラスタに対して、アプリケーションのクローンまたはリストアを実行できます。ただし、同じユーザが、クローニングまたはリストアされたアプリケーションに新しいネームスペースからアクセスすることはできません。クローンまたはリストア処理によって新しいネームスペースが作成されると、アカウントの管理者 / 所有者はメンバーユーザアカウントを編集し、該当するユーザに新しいネームスペースへのアクセスを許可するロールの制限を更新できます。
* *クローンはデフォルトバケットを使用*：
+
** アプリケーションのバックアップやアプリケーションのリストア中に、使用するバケットを指定できます。クラスタ間でクローニングする場合、デフォルトバケットを指定する必要がありますが、同じクラスタ内でクローニングする場合、バケットの指定は任意です。
** クラスタ間でクローニングする場合、クローン処理のソースクラスタを含むクラウドインスタンスには、デフォルトのバケットセットが必要です。
** クローンのバケットを変更するオプションはありません。どのバケットを使用するかを制御する必要がある場合は、どちらかを選択できます link:../use/manage-buckets.html#edit-a-bucket["バケットのデフォルト設定を変更する"] または、を実行します link:../use/protect-apps.html#create-a-backup["バックアップ"] その後にを押します link:../use/restore-apps.html["リストア"] 個別。


* * Jenkins CI*を使用：オペレータがデプロイしたJenkins CIのインスタンスをクローニングする場合は、永続データを手動で復元する必要があります。これは、アプリケーションの展開モデルの制限事項です。


.手順
. 「 * アプリケーション * 」を選択します。
. 次のいずれかを実行します。
+
** 目的のアプリケーションの [ * アクション * （ * Actions * ） ] 列で [ オプション（ Options ） ] メニューを選択します。
** 目的のアプリケーションの名前を選択し、ページの右上にあるステータスドロップダウンリストを選択します。


. 「 * Clone * 」を選択します。
. クローンの詳細を指定します。
+
** 名前を入力します。
** クローンのデスティネーションクラスタを選択してください。
** クローンのデスティネーションネームスペースを入力してください。アプリケーションに関連付けられている各ソースネームスペースは、デスティネーションネームスペースにマッピングされます。
+

NOTE: Astra Controlでは、クローニング処理の一環として新しいデスティネーションネームスペースが作成されます。指定するデスティネーションネームスペースがデスティネーションクラスタに存在していないことを確認してください。

** 「 * 次へ * 」を選択します。
** 既存の Snapshot からクローンを作成するかバックアップを作成するかを選択します。このオプションを選択しない場合は、 Astra Control がアプリケーションの現在の状態からクローンを作成します。
+
*** 既存のSnapshotまたはバックアップからクローニングする場合は、使用するSnapshotまたはバックアップを選択します。




. 「 * 次へ * 」を選択します。
. クローンに関する情報を確認し、* Clone *を選択します。


.結果
Astra Controlは、入力した情報に基づいてアプリケーションをクローニングします。新しいアプリケーションクローンがに含まれている場合、クローニング処理は成功します `Healthy` 「*アプリケーション*」ページで説明します。

クローンまたはリストア処理によって新しいネームスペースが作成されると、アカウントの管理者 / 所有者はメンバーユーザアカウントを編集し、該当するユーザに新しいネームスペースへのアクセスを許可するロールの制限を更新できます。
