---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: クラウドプロバイダのクレデンシャルをアカウントにいつでも追加、削除できます。Astra Control は、これらの資格情報を使用して、お客様に代わってリソースをプロビジョニングします。 
---
= クレデンシャルを追加および削除します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
クラウドプロバイダのクレデンシャルをアカウントにいつでも追加、削除できます。Astra Control は、 Kubernetes クラスタとクラスタ上のアプリケーションを検出し、ユーザに代わってリソースをプロビジョニングするために、このクレデンシャルを使用します。

Astra Control のすべてのユーザが同じクレデンシャルセットを共有していることに注意してください。



== クレデンシャルを追加する

Astra Control にクレデンシャルを追加する最も一般的な方法は、クラスタを管理する場合ですが、アカウントページからクレデンシャルを追加することもできます。その後、 Kubernetes クラスタを追加で管理する際にクレデンシャルを選択できるようになります。

ifdef::aws[]

* Amazon Web Servicesの場合、クラスタの作成に使用するIAMアカウントのクレデンシャルのJSON出力が必要です。 link:../get-started/set-up-amazon-web-services.html["IAMユーザを設定する方法を説明します"]。


endif::aws[]

ifdef::gcp[]

* GKE の場合は、必要な権限を持つサービスアカウントのサービスアカウントキーファイルが必要です。 link:../get-started/set-up-google-cloud.html["サービスアカウントの設定方法について説明します"]。


endif::gcp[]

ifdef::azure[]

* AKS の場合、サービスプリンシパルの作成時に Azure CLI からの出力を含む JSON ファイルが必要です。 link:../get-started/set-up-microsoft-azure-with-anf.html["サービスプリンシパルの設定方法について説明します"]。
+
JSON ファイルに追加していない場合は、 Azure サブスクリプション ID も必要になります。



endif::azure[]

.手順
. [*Account] > [Credentials] を選択します。
. [Add Credentials] を選択します。


ifdef::azure[]

. Microsoft Azure *を選択します。


endif::azure[]

ifdef::gcp[]

. [* Google Cloud Platform*]を選択します。


endif::gcp[]

ifdef::aws[]

. Amazon Web Servicesを選択します。


endif::aws[]

. Astra Control の他のクレデンシャルと区別するクレデンシャルの名前を入力します。
. 必要なクレデンシャルを入力します。


ifdef::azure[]

. * Microsoft Azure * ： JSON ファイルをアップロードするか、クリップボードから JSON ファイルの内容を貼り付けて、 Azure サービスプリンシパルの詳細を Astra Control に伝えます。
+
JSON ファイルに、サービスプリンシパルの作成時に Azure CLI からの出力が含まれている必要があります。サブスクリプション ID を含めることで、 Astra Control に自動的に追加されるようにすることもできます。ID が必要な場合は、 JSON の指定後に手動で ID を入力する必要があります。



endif::azure[]

ifdef::gcp[]

. * Google Cloud Platform * ：ファイルをアップロードするか、クリップボードからコンテンツを貼り付けて、 Google Cloud サービスアカウントのキーファイルを提供します。


endif::gcp[]

ifdef::aws[]

. * Amazon Web Services *：ファイルをアップロードするか、クリップボードから内容を貼り付けて、Amazon Web Services IAMユーザクレデンシャルを指定します。


endif::aws[]

. [Add Credentials] を選択します。


これで、 Astra Control にクラスタを追加するときに、クレデンシャルを選択できるようになりました。



== クレデンシャルを削除する

アカウントからのクレデンシャルの削除はいつでも実行できます。クレデンシャルは、のあとに削除してください link:unmanage.html["すべてのクラスタの管理を解除します"]（認証情報のローテーションを実行していない場合）  credentials）。


NOTE: Astra Control に追加する最初のクレデンシャルセットは常に使用されています。 Astra Control は、そのクレデンシャルを使用してバックアップバケットへの認証を行うためです。これらのクレデンシャルは削除しないことを推奨します。

.手順
. [*Account] > [Credentials] を選択します。
. 削除するクレデンシャルの「 * State * 」列でドロップダウンリストを選択します。
. 「 * 削除」を選択します。
. 削除を確認するために資格情報の名前を入力し、 * はい、資格情報を削除 * を選択します。


Astra Control は、アカウントからクレデンシャルを削除します。



== クレデンシャルのローテーション

アカウント内でクレデンシャルをローテーションすることができます。クレデンシャルのローテーションを行う場合は、バックアップが進行中でないとき（スケジュール設定またはオンデマンド）に、ローテーションを継続して実行してください。

.手順
. の手順に従って、既存のクレデンシャルを削除します  credentials。
. の手順に従って、新しいクレデンシャルを追加します  credentials。
. 新しいクレデンシャルを使用するようにすべてのバケットを更新します。
+
.. 左側のナビゲーションから、*バケット*を選択します。
.. 編集するバケットの「 * Actions * 」列でドロップダウンリストを選択します。
.. 「 * 編集 * 」を選択します。
.. 資格情報の選択*セクションで、Astra Controlに追加した新しい資格情報を選択します。
.. 「 * Update * 」を選択します。
.. システムの残りのバケットに対して、手順* b *~* e *を繰り返します。




Astra Controlが新しいクラウドプロバイダのクレデンシャルの使用を開始。
