---
sidebar: sidebar 
permalink: use/manage-roles.html 
keywords: users, roles, user roles, namespace, namespaces, account, accounts, permissions, restriction, restrict, constraint, constraints 
summary: ロールに制約を追加してユーザロールを管理する方法について説明します。 
---
= ロールの管理
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
ロールを管理するには、ネームスペースの制約を追加し、ユーザロールをその制約に制限します。これにより、組織内のリソースへのアクセスを制御できます。Astra Control UI またはを使用できます https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] をクリックしてください。



== ロールに名前空間制約を追加します

Admin または Owner ユーザは、ネームスペースの制約を追加できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*Users*] タブを選択します。
. [ * アクション * （ * Actions * ） ] 列で、メンバーまたはビューアーの役割を持つユーザーのメニューボタンを選択します。
. [ 役割の編集 ] を選択します。
. [ ロールを制約に制限する *] チェックボックスをオンにします。
+
このチェックボックスは、メンバーロールまたはビューアロールでのみ使用できます。[*Role] ドロップダウン・リストから別のロールを選択できます

. [ * 制約の追加 * ] を選択します。
+
使用可能な制約の一覧は、ネームスペースまたはネームスペースラベルで確認できます。

. [ 制約タイプ * （ Constraint type * ） ] ドロップダウンリストで、ネームスペースの構成方法に応じて、 [* Kubernetes namespace] * または [* Kubernetes namespace label* ] を選択します。
. リストから 1 つ以上の名前空間またはラベルを選択して、それらの名前空間にロールを制限する制約を構成します。
. [* 確認 *] を選択します。
+
[ 役割の編集 *] ページには、この役割に選択した拘束のリストが表示されます。

. [* 確認 *] を選択します。
+
[*Account*] ページでは、 [*Role] 列のメンバまたはビューアの役割の制約を表示できます。




NOTE: 制約を追加せずに役割の制約を有効にし、 * 確認 * を選択すると、役割には完全な制限があると見なされます（役割は、名前空間に割り当てられているリソースへのアクセスを拒否されます）。



== ロールから名前空間制約を削除します

管理者または所有者ユーザーは、役割から名前空間の制約を削除できます。

.手順
. 「アカウントの管理」ナビゲーション領域で、「 * アカウント * 」を選択します。
. [*Users*] タブを選択します。
. [ * アクション * （ * Actions * ） ] 列で、アクティブな拘束を持つメンバーまたはビューアーの役割を持つユーザーのメニューボタンを選択する。
. [ 役割の編集 ] を選択します。
+
* 役割の編集 * （ Edit role * ）ダイアログには、役割のアクティブな拘束が表示されます。

. 削除する拘束の右側にある * X * を選択します。
. [* 確認 *] を選択します。




== を参照してください。

* link:../learn/user-roles-namespaces.html["ユーザロールとネームスペース"]

