---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: invite users, add users, remove users, delete users 
summary: ユーザーを Astra Control アカウントに招待し、アカウントにアクセスできなくなったユーザーを削除します。 
---
= ユーザーを招待および削除します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
ユーザーを Astra Control アカウントに招待し、アカウントにアクセスできなくなったユーザーを削除します。



== ユーザーを招待します

アカウント所有者と管理者は、他のユーザを Astra Control アカウントに招待できます。

.手順
. ユーザにが割り当てられていることを確認します link:../get-started/register.html["Cloud Central へのログイン"]。
. 「 * アカウント * 」を選択します。
. [* ユーザー * ] タブで、 [* 招待 * ] を選択します。
. ユーザの名前、 E メールアドレス、およびロールを入力します。
+
次の点に注意してください。

+
** E メールアドレスが、 Cloud Central へのサインアップに使用した E メールアドレスと一致している必要があります。
** 各ロールには次の権限があります。
+
*** * 所有者 * には管理者権限があり、アカウントを削除できます。
*** * Admin * にはメンバー権限があり、他のユーザーを招待できます。
*** メンバー * は、アプリとクラスターを完全に管理できます。
*** * Viewer * はリソースを表示できます。




. メンバーロールまたはビューアロールを持つユーザーに制約を追加するには、 * 制約へのロールの制限 * チェックボックスをオンにします。
+
拘束の追加の詳細については、を参照してください link:manage-roles.html["ロールの管理"]。

. 別のユーザーを招待するには、 * 別のユーザーを追加 * を選択し、新しいユーザーの情報を入力します。
+
一度に最大 10 人のユーザーを招待できます。[ ユーザーの招待 ] ダイアログの左側で、招待するユーザー間をナビゲートできます。

. [* ユーザーを招待する * ] を選択します。


.結果
ユーザーには、アカウントへの参加を招待する電子メールが送信されます。



== ユーザのロールを変更します

Account Owner はすべてのユーザのロールを変更できますが、 Account Admin は、 Admin 、 Member 、 Viewer のいずれかのロールを持つユーザのロールを変更できます。

.手順
. 「 * アカウント * 」を選択します。
. [ * ユーザー * ] タブで、ユーザーの [ * アクション * ] 列のメニューを選択します。
. [ 役割の編集 ] を選択します。
. 新しいロールを選択します。
. メンバーロールまたはビューアロールを持つユーザーに制約を追加するには、 * 制約へのロールの制限 * チェックボックスをオンにします。
+
拘束の追加の詳細については、を参照してください link:manage-roles.html["ロールの管理"]。

. [* 確認 *] を選択します。


.結果
Astra Control は、選択した新しいロールに基づいてユーザーの権限を更新します。



== ユーザを削除します

所有者ロールを持つユーザーは、いつでもそのアカウントから他のユーザーを削除できます。

.手順
. 「 * アカウント * 」を選択します。
. [* ユーザー * ] タブで、削除するユーザーを選択します。
. [* アクション * （ * Actions * ） ] 列のメニューを選択し、 [ * ユーザーの削除 * （ Remove user * ） ] を選択します
. プロンプトが表示されたら、「 remove 」と入力して削除を確認し、「 * Yes 、 Remove User * 」を選択します。


.結果
Astra Control を使用すると、アカウントからユーザが削除されます。
