---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: Astra がバックアップとクローンに使用するバケットを管理するには、バケットを追加し、クラウドプロバイダ内のクラスタのデフォルトバケットを変更します。 
---
= バケットを管理する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Astra がバックアップとクローンに使用するバケットを管理するには、バケットを追加し、クラウドプロバイダ内の Kubernetes クラスタのデフォルトバケットを変更します。

バケットを追加および変更できるのは Admin のみです。



== Astra Control でのバケットの使用方法

最初の Kubernetes クラスタの管理を開始すると、 Astra Control Service が、管理対象クラスタと同じ場所にクラウドプロバイダのデフォルトバケットを作成します。

Astra Control Service は、作成したバックアップとクローンにこのデフォルトバケットを使用します。その後、バックアップを使用して、クラスタ間でアプリケーションのリストアやクローニングを行うことができます。

Astra Control Service にバケットを追加する場合は、保護ポリシーの作成時にこれらのバケットから選択できます。また、 Astra Control Service がアドホックバックアップやクローンに使用するデフォルトバケットを変更することもできます。クラウドプロバイダ間でバケットをクローニングすることはできません。クラウドプロバイダ間でデータを移行するには、関連するアプリケーションのクローンを作成します。


TIP: Astra Control Service は、バックアップまたはクローンを開始する前に、デスティネーションバケットがアクセス可能かどうかをチェックします。



== 既存のバケットを表示します

Astra Control Service で使用可能なバケットのリストを表示して、クラウドプロバイダのステータスを確認したり、デフォルトのバケットを特定したりできます。

バケットの状態は次のいずれかになります。

保留中です:: バケットを追加すると、最初に Pending 状態から Astra Control が初めてバケットを参照します。
利用可能:: バケットは Astra Control で使用できます。
削除されました:: このバケットは現在動作していません。ステータスアイコンの上にマウスポインタを合わせると、問題の内容がわかります。
+
--
バケットが Removed 状態の場合でも、バケットをデフォルトのバケットとして設定し、保護スケジュールに割り当てることができます。ただし、データ保護処理の開始時点でバケットが「 available 」状態でない場合は、処理が失敗します。

--


.ステップ
. [ * ストレージの管理 * ] で、 [ * バケット * ] を選択します。
+
Astra Control Service で使用できるバケットのリストが表示されます。





== 追加のバケットを追加します

クラウドプロバイダでクラスタの管理を開始したら、いつでもバケットを追加できます。これにより、保護ポリシーの作成時にバケットを選択したり、アドホックバックアップやクローンのデフォルトバケットを変更したりできます。

Astra Control Service では、バケットを追加したあとに削除できないことに注意してください。

.必要なもの
* クラウドプロバイダ内の既存のバケットの名前。
* バケットが Azure 内にある場合は、 _Astra -backup -rg_ という名前のリソースグループに属している必要があります。


.手順
. [ * ストレージの管理 * ] で、 [ * バケット * ] を選択します。
. 「 * Add * 」を選択し、プロンプトに従ってバケットを追加します。
+
** * タイプ * ：クラウドプロバイダを選択します。
+
クラウドプロバイダを利用できるのは、 Astra Control Service がクラウドプロバイダで実行されているクラスタの管理を開始したあとのみです。

** * 既存のバケット名 * ：バケットの名前を入力します。
** * 概要 * ：必要に応じて、バケットの概要を入力します。
** * このバケットをこのクラウドのデフォルトバケットにする * ：このバケットをアドホックバックアップやクローンのデフォルトバケットとして使用するかどうかを選択します。
** * クレデンシャルを選択 * ：バケットを管理するために必要な権限を Astra Control Service に付与するクレデンシャルを選択します。


. 「 * Add * 」を選択してバケットを追加します。


Astra Control Service は、追加のバケットを追加します。保護ポリシーの作成時にバケットを選択できるようになりました。



== デフォルトバケットを変更する

バックアップとクローンに Astra Control Service で使用するデフォルトバケットを変更する。各クラウドプロバイダには、独自のデフォルトバケットがあります。

Astra Control Service では、クラウドプロバイダ用のデフォルトバケットを使用して、既存のバックアップからクローニングすることを選択しなかった場合に、アドホックバックアップやアドホッククローンを作成します。

.手順
. [ * ストレージの管理 * ] で、 [ * バケット * ] を選択します。
. 編集するバケットの「 * Actions * 」列でドロップダウンリストを選択します。
. このバケットをこのクラウドのデフォルトバケットにする * を選択します。
. 「 * Update * 」を選択します。




== バケットを削除する

使用されなくなったバケットや正常でないバケットを削除することができます。これは、オブジェクトストアの設定をシンプルかつ最新の状態に保つために役立ちます。

デフォルトバケットを削除することはできません。そのバケットを削除する場合は、最初に別のバケットをデフォルトとして選択します。

.必要なもの
* 開始する前に、このバケットの実行中または完了済みのバックアップがないことを確認してください。
* スケジュールされたバックアップにバケットが使用されていないことを確認する必要があります。


ある場合は、続行できません。

.手順
. 左ナビゲーションから、 * バケット * を選択します。
. [ アクション * （ Actions * ） ] メニューから、 [ * 削除（ Remove ） ] を選択します。
+

NOTE: Astra Control を使用すると、最初にバケットを使用してバックアップを実行するスケジュールポリシーが存在せず、削除しようとしているバケットにアクティブなバックアップが存在しないようにすることができます。

. 「 remove 」と入力して操作を確認します。
. 「 * Yes 、 remove bucket * 」を選択します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API を使用"^]

