---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: Astra がバックアップとクローンに使用するバケットを管理するには、バケットを追加し、クラウドプロバイダ内のクラスタのデフォルトバケットを変更します。 
---
= バケットを管理する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astraがバックアップとクローンに使用するバケットを管理できます。バケットの追加、既存のバケットの削除、クラウドインスタンス内のKubernetesクラスタのデフォルトバケットの変更を行うことができます。

バケットを管理できるのは、所有者と管理者だけです。



== Astra Control でのバケットの使用方法

クラウドインスタンスの最初のKubernetesクラスタの管理を開始すると、Astra Control Serviceによってそのクラスタ用の初期バケットが作成されます link:manage-cloud-instances.html["クラウドインスタンス"^]。

バケットをクラウドインスタンスのデフォルトバケットとして手動で指定できます。その場合、Astra Control Serviceでは、そのクラウドインスタンス内の管理対象クラスタに作成したバックアップとクローンに対して、デフォルトでこのバケットが使用されます（バックアップ用に別のバケットを選択できます）。クラウドインスタンス内の管理対象クラスタから別のクラスタにアプリケーションのライブクローンを実行する場合、Astra Control Serviceはソースクラウドインスタンスのデフォルトバケットを使用してクローニング処理を実行します。

複数のクラウドインスタンスのデフォルトバケットと同じバケットを設定できます。

保護ポリシーの作成時またはアドホックバックアップの開始時に、任意のバケットから選択できます。


TIP: Astra Control Service は、バックアップまたはクローンを開始する前に、デスティネーションバケットがアクセス可能かどうかをチェックします。



== 既存のバケットを表示します

Astra Control Serviceで使用可能なバケットのリストを表示して、そのステータスを確認し、クラウドインスタンスのデフォルトバケット（定義されている場合）を特定します。

バケットの状態は次のいずれかになります。

保留中です:: 追加したバケットは保留状態で開始され、Astra Controlが検出します。
利用可能:: バケットは Astra Control で使用できます。
削除されました:: このバケットは現在動作していません。ステータスアイコンの上にマウスポインタを合わせると、問題の内容がわかります。
+
--
バケットが Removed 状態の場合でも、バケットをデフォルトのバケットとして設定し、保護スケジュールに割り当てることができます。ただし、データ保護処理の開始時点でバケットが「 available 」状態でない場合は、処理が失敗します。

--


.ステップ
. 「*バケット」に移動します。
+
Astra Control Serviceで使用可能なバケットのリストが表示されます。





== 追加のバケットを追加します

バケットはいつでも追加できます。これにより、保護ポリシーの作成時またはアドホックバックアップの開始時にバケットを選択したり、クラウドインスタンスが使用するデフォルトのバケットを変更したりできます。

次のタイプのバケットを追加できます。

* Amazon Web Services の
* 汎用 S3
* Google Cloud Platform の 1 つです
* Microsoft Azure
* NetApp ONTAP S3
* NetApp StorageGRID S3 の略


.作業を開始する前に
* 既存のバケットの名前。
* Astra Control Serviceにバケットの管理に必要な権限を付与するバケットのクレデンシャル。


ifdef::azure[]

* バケットがMicrosoft Azureにある場合：
+
** バケットは、_Astra -backup-rg_というリソースグループに属している必要があります。
** Azureストレージアカウントインスタンスのパフォーマンス設定が「Premium」に設定されている場合は、「Premium account type」設定を「Block blobs」に設定する必要があります。




endif::azure[]

.手順
. 「*バケット」に移動します。
. 「 * Add * 」を選択し、プロンプトに従ってバケットを追加します。
+
** * タイプ * ：クラウドプロバイダを選択します。
** * 既存のバケット名 * ：バケットの名前を入力します。
** * 概要 * ：必要に応じて、バケットの概要を入力します。




ifdef::azure[]

* *ストレージアカウント*（Azureのみ）：Azureストレージアカウントの名前を入力します。このバケットは、_Astra -backup-rg_というリソースグループに属している必要があります。


endif::azure[]

ifdef::aws[]

* * S3サーバ名またはIPアドレス*（AWSおよびS3バケットタイプのみ）：リージョンに対応するS3エンドポイントの完全修飾ドメイン名を、なしで入力します `https://`。を参照してください https://docs.aws.amazon.com/general/latest/gr/s3.html["Amazonのドキュメント"^] を参照してください。


endif::aws[]

* *クレデンシャルを選択*：Astra Control Serviceにバケットの管理に必要な権限を付与するクレデンシャルを入力します。指定する必要がある情報は、バケットタイプによって異なります。
+
.. 「 * Add * 」を選択してバケットを追加します。




.結果
Astra Control Serviceでバケットが追加されます。このバケットは、保護ポリシーの作成時やアドホックバックアップの実行時に選択できるようになりました。このバケットをクラウドインスタンスのデフォルトバケットとして設定することもできます。



== デフォルトバケットを変更する

クラウドインスタンスのデフォルトバケットを変更できます。Astra Control Serviceでは、デフォルトでバックアップとクローンにこのバケットが使用されます。各クラウドインスタンスには、独自のデフォルトバケットがあります。


NOTE: Astra Controlでは、どのクラウドインスタンスに対してもデフォルトのバケットが自動的に割り当てられることはありません。2つのクラスタ間でアプリケーションのクローニング処理を実行する前に、クラウドインスタンスのデフォルトバケットを手動で設定する必要があります。

.手順
. 「* Cloud Instances *」に移動します。
. 編集するクラウドインスタンスの[*アクション*（* Actions *）]列で構成メニューを選択します。
. 「 * 編集 * 」を選択します。
. バケットのリストで、このクラウドインスタンスのデフォルトバケットにするバケットを選択します。
. 「 * Update * 」を選択します。




== バケットを削除する

使用されなくなったバケットや正常でないバケットを削除することができます。これは、オブジェクトストアの設定をシンプルかつ最新の状態に保つために役立ちます。

デフォルトバケットを削除することはできません。そのバケットを削除する場合は、最初に別のバケットをデフォルトとして選択します。

.作業を開始する前に
* 開始する前に、このバケットの実行中または完了済みのバックアップがないことを確認してください。
* スケジュールされたバックアップにバケットが使用されていないことを確認する必要があります。


ある場合は、続行できません。

.手順
. 「*バケット」に移動します。
. [ アクション * （ Actions * ） ] メニューから、 [ * 削除（ Remove ） ] を選択します。
+

NOTE: Astra Control を使用すると、最初にバケットを使用してバックアップを実行するスケジュールポリシーが存在せず、削除しようとしているバケットにアクティブなバックアップが存在しないようにすることができます。

. 「 remove 」と入力して操作を確認します。
. 「 * Yes 、 remove bucket * 」を選択します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API を使用"^]

