---
sidebar: sidebar 
permalink: use/monitor-running-tasks.html 
keywords: activity, log, activities, running, tasks, monitor, status, state 
summary: Astra Controlで実行中のタスクの詳細を表示できます。たとえば、スナップショット、バックアップ、クローンを実行する場合などです。 
---
= 実行中のタスクを監視します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Controlの過去24時間に完了、失敗、またはキャンセルされた実行中のタスクとタスクの詳細を表示できます。たとえば、実行中のバックアップ、リストア、またはクローン処理のステータスを表示して、完了した割合や推定残り時間などの詳細を確認できます。実行済みのスケジュール済み処理または手動で開始した処理のステータスを表示できます。

実行中または完了済みのタスクを表示している間に、タスクの詳細を展開して、各サブタスクのステータスを確認できます。進行中のタスクまたは完了したタスクの場合はタスクの進捗状況バーが緑色で表示され、キャンセルされたタスクの場合は青色で表示され、エラーのために失敗したタスクの場合は赤色で表示されます。


NOTE: クローン処理の場合、タスクサブタスクはSnapshotとSnapshotのリストア処理で構成されます。

失敗したタスクの詳細については、を参照してください link:monitor-account-activity.html["アカウントのアクティビティを監視"]。

.手順
. タスクの実行中に、「*アプリケーション*」に移動します。
. リストからアプリケーションの名前を選択します。
. アプリケーションの詳細で、[*タスク*]タブを選択します。
+
現在または過去のタスクの詳細を表示したり、タスクの状態でフィルタリングしたりできます。




NOTE: タスクは最大24時間、*タスク*リストに保存されます。を使用して、この制限とその他のタスクモニタの設定を行うことができます https://["Astra Control API の略"^]。
