---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore 
summary: Astra Control を使用すると、スナップショットまたはバックアップからアプリケーション構成と永続的ストレージをリストアできます。オブジェクトストアから永続的ストレージのバックアップが転送されるため、既存のバックアップからのリストアが最も高速に完了します。 
---
= アプリケーションのリストア
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control を使用すると、スナップショットまたはバックアップからアプリケーションをリストアできます。同じクラスタにアプリケーションをリストアする場合、既存の Snapshot からのリストアは高速です。Astra Control UI またはを使用できます https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] アプリを復元するには、

.手順
. 「 * アプリケーション」を選択し、管理アプリの名前を選択します。
. 「 * データ保護 * 」を選択します。
. Snapshot からリストアする場合は、「 * Snapshot * 」を選択したままにします。それ以外の場合は、「 * Backups * 」を選択してバックアップからリストアします。
. リストアする Snapshot またはバックアップの * Actions * 列で、ドロップダウンリストを選択します。
. [ アプリケーションの復元 ] を選択します。
. * リストアの詳細 * ：リストアされたアプリの詳細を指定します。アプリをインプレースで復元する（アプリを以前のバージョンのアプリに戻す）には、現在実行している名前空間クラスタとデスティネーションクラスタを選択します。
+
** アプリケーションのネームスペースを入力します。
** アプリケーションのデスティネーションクラスタを選択します。
** [* Review （レビュー） ] をクリックします


. * リストアの概要 * ：リストア操作の詳細を確認し、「 restore 」と入力して、 * Restore * を選択します。


Astra Control は、指定した情報に基づいてアプリケーションを復元します。アプリケーションをインプレースでリストアした場合、関連付けられている永続ボリュームは削除され、再作成されます。
