---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore, migrate nas-economy 
summary: Astra Control を使用すると、スナップショットまたはバックアップからアプリケーション構成と永続的ストレージをリストアできます。オブジェクトストアから永続的ストレージのバックアップが転送されるため、既存のバックアップからのリストアが最も高速に完了します。 
---
= アプリケーションのリストア
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control を使用すると、スナップショットまたはバックアップからアプリケーションをリストアできます。同じクラスタにアプリケーションをリストアする場合、既存の Snapshot からのリストアは高速です。Astra Control UI またはを使用できます https://["Astra Control API"^] アプリを復元するには、


NOTE: リストアまたはクローン処理のあとに実行される実行フックにネームスペースフィルタを追加し、リストアまたはクローンのソースとデスティネーションが異なるネームスペースにある場合、ネームスペースフィルタはデスティネーションネームスペースにのみ適用されます。

.このタスクについて
* *最初にアプリケーションを保護する*:アプリケーションを復元する前に、アプリケーションのスナップショットまたはバックアップを作成することを強くお勧めします。リストアに失敗した場合に、Snapshotまたはバックアップからクローニングできます。
* *デスティネーションボリュームを確認*：別のクラスタにリストアする場合は、同じ永続的ボリュームアクセスモード（ReadWriteManyなど）をクラスタが使用していることを確認してください。デスティネーションの永続ボリュームアクセスモードが異なると、リストア処理は失敗します。
* *必要なスペースを確保するための計画*：NetApp ONTAP ストレージを使用するアプリケーションのインプレースリストアを実行すると、リストアしたアプリケーションで使用されるスペースが2倍になることがあります。In Placeリストアを実行したあとに、リストアしたアプリケーションから不要なSnapshotを削除して、ストレージスペースを解放します。


[CAUTION]
====
リソースを共有するアプリケーションでIn Placeリストア処理を実行すると、予期しない結果が生じる可能性があります。アプリケーション間で共有されているリソースは、いずれかのアプリケーションでインプレースリストアが実行されると置き換えられます。

====
.手順
. 「 * アプリケーション」を選択し、アプリケーションの名前を選択します。
. [オプション]メニューの[操作]列で、*[リストア]*を選択します。
. リストアタイプを選択します。
+
** *元のネームスペースにリストア*：この手順 を使用して、アプリケーションを元のクラスタにインプレースでリストアします。
+
... アプリをインプレースで復元するために使用するスナップショットまたはバックアップを選択します。これにより、アプリは以前のバージョンに戻ります。
... 「 * 次へ * 」を選択します。
+

NOTE: 以前に削除したネームスペースにリストアすると、同じ名前の新しいネームスペースがリストアプロセスで作成されます。以前に削除したネームスペースでアプリケーションを管理する権限を持つユーザは、新しく作成したネームスペースに手動で権限を復元する必要があります。



** *新しい名前空間に復元*：この手順 を使用して、アプリを別のクラスタまたはソースとは異なる名前空間で別のクラスタに復元します。
+
... 復元されたアプリの名前を指定します。
... リストアするアプリケーションのデスティネーションクラスタを選択します。
... アプリケーションに関連付けられている各ソースネームスペースのデスティネーションネームスペースを入力します。
+

NOTE: Astra Controlは、このリストアオプションの一部として新しいデスティネーションネームスペースを作成します。指定するデスティネーションネームスペースがデスティネーションクラスタに存在していないことを確認してください。

... 「 * 次へ * 」を選択します。
... アプリの復元に使用するスナップショットまたはバックアップを選択します。
... 「 * 次へ * 」を選択します。




. フィルタするリソースを選択：
+
** *すべてのリソースを復元*：元のアプリケーションに関連付けられているすべてのリソースを復元します。
** *リソースのフィルタ*:元のアプリケーションリソースのサブセットを復元するルールを指定します。
+
... リストアされたアプリケーションにリソースを含めるか除外するかを選択します。
... [含めるルールを追加]*または*[除外ルールを追加]*のいずれかを選択し、アプリケーションのリストア時に正しいリソースをフィルタするようにルールを設定します。設定が正しくなるまで、ルールを編集したり削除したり、ルールを再度作成したりすることができます。
+

NOTE: includeルールとexcludeルールの設定については、を参照してください <<アプリケーションのリストア中にリソースをフィルタリングします>>。





. 「 * 次へ * 」を選択します。
. リストア処理の詳細をよく確認し、プロンプトが表示されたら「restore」と入力して*[リストア]*を選択します。


.結果
Astra Control は、指定した情報に基づいてアプリケーションを復元します。アプリケーションをインプレースでリストアした場合、既存の永続ボリュームのコンテンツが、リストアしたアプリケーションの永続ボリュームのコンテンツに置き換えられます。


NOTE: データ保護処理（クローン、バックアップ、またはリストア）が完了して永続ボリュームのサイズを変更したあと、Web UIに新しいボリュームサイズが表示されるまでに最大20分かかります。データ保護処理にかかる時間は数分です。また、ストレージバックエンドの管理ソフトウェアを使用してボリュームサイズの変更を確認できます。


NOTE: ネームスペースの名前/ IDまたはネームスペースのラベルでネームスペースの制約を受けているメンバーユーザは、同じクラスタの新しいネームスペース、または組織のアカウントに含まれる他のクラスタにアプリケーションをクローニングまたはリストアできます。ただし、同じユーザが、クローニングまたはリストアされたアプリケーションに新しいネームスペースからアクセスすることはできません。クローンまたはリストア処理によって新しいネームスペースが作成されると、アカウントの管理者 / 所有者はメンバーユーザアカウントを編集し、該当するユーザに新しいネームスペースへのアクセスを許可するロールの制限を更新できます。



== アプリケーションのリストア中にリソースをフィルタリングします

にフィルタルールを追加できます link:../use/restore-apps.html["リストア"] リストアされたアプリケーションに含める、またはリストアされたアプリケーションから除外する既存のアプリケーションリソースを指定する処理。指定した名前空間、ラベル、またはGVK（GroupVersionKind）に基づいて、リソースを含めたり除外したりできます。

.対象と除外のシナリオについて詳しくは、こちらをご覧ください
[%collapsible]
====
* *元のネームスペースを使用する包含ルールを選択した場合（インプレースリストア）*：ルールで定義した既存のアプリケーションリソースは削除され、リストアに使用する選択したSnapshotまたはバックアップのリソースで置き換えられます。includeルールで指定しないリソースは変更されません。
* *新しい名前空間を持つincludeルールを選択した場合*：このルールを使用して、リストアされたアプリケーションで使用する特定のリソースを選択します。対象ルールに指定しないリソースは、リストアされたアプリケーションには含まれません。
* *元のネームスペースを含む除外ルールを選択した場合（インプレースリストア）*：除外するように指定したリソースはリストアされず、変更されません。除外するように指定しないリソースは、スナップショットまたはバックアップからリストアされます。対応するStatefulSetがフィルタリングされたリソースに含まれている場合、永続ボリューム上のすべてのデータが削除されて再作成されます。
* *新しい名前空間を持つ除外ルールを選択した場合*:このルールを使用して、リストアされたアプリケーションから削除する特定のリソースを選択します。除外するように指定しないリソースは、スナップショットまたはバックアップからリストアされます。


====
ルールには、includeまたはexcludeタイプがあります。リソースの包含と除外を組み合わせたルールは使用できません。

.手順
. リソースをフィルタするように選択し、[アプリケーションのリストア]ウィザードで[含める]または[除外するルールを追加する]を選択したら、*[除外するルールを追加する]*を選択します。
+

NOTE: Astra Controlで自動的に追加されるクラスタ対象のリソースを除外することはできません。

. フィルタルールを設定します。
+

NOTE: ネームスペース、ラベル、またはGVKを少なくとも1つ指定する必要があります。フィルタルールを適用したあとに保持するリソースがあれば、リストアしたアプリケーションを正常な状態に保つのに十分であることを確認してください。

+
.. ルールの特定のネームスペースを選択します。選択しない場合は、すべての名前空間がフィルタで使用されます。
+

NOTE: アプリケーションに複数のネームスペースが含まれていた場合、新しいネームスペースにリストアすると、リソースが含まれていなくてもすべてのネームスペースが作成されます。

.. （オプション）リソース名を入力します。
.. （任意）*ラベルセレクタ*：を含めます https://["ラベルセレクタ"^] をクリックしてルールに追加します。ラベルセレクタは、選択したラベルに一致するリソースのみをフィルタリングするために使用されます。
.. （オプション）[Use GVK (GroupVersionKind) set]を選択してリソースをフィルタリング*し、追加のフィルタリングオプションを指定します。
+

NOTE: GVKフィルタを使用する場合は、バージョンと種類を指定する必要があります。

+
... （オプション）* Group *：ドロップダウンリストからKubernetes APIグループを選択します。
... *種類*：ドロップダウンリストから、フィルタで使用するKubernetesリソースタイプのオブジェクトスキーマを選択します。
... *バージョン*：Kubernetes APIのバージョンを選択します。




. エントリに基づいて作成されたルールを確認します。
. 「 * 追加」を選択します。
+

TIP: ルールを含むリソースと除外するリソースは必要なだけ作成できます。処理を開始する前に、リストアアプリケーションの概要にルールが表示されます。


