---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore 
summary: Astra Control を使用すると、スナップショットまたはバックアップからアプリケーション構成と永続的ストレージをリストアできます。オブジェクトストアから永続的ストレージのバックアップが転送されるため、既存のバックアップからのリストアが最も高速に完了します。 
---
= アプリケーションのリストア
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control を使用すると、スナップショットまたはバックアップからアプリケーションをリストアできます。同じクラスタにアプリケーションをリストアする場合、既存の Snapshot からのリストアは高速です。Astra Control UI またはを使用できます https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] アプリを復元するには、


NOTE: NetApp ONTAP ストレージを使用するアプリケーションのIn Placeリストアを実行すると、リストアしたアプリケーションで使用するスペースは2倍になります。In Placeリストアを実行したあとに、リストアしたアプリケーションから不要なSnapshotを削除して、ストレージスペースを解放します。


NOTE: リストアまたはクローン処理のあとに実行される実行フックにネームスペースフィルタを追加し、リストアまたはクローンのソースとデスティネーションが異なるネームスペースにある場合、ネームスペースフィルタはデスティネーションネームスペースにのみ適用されます。

.このタスクについて
* *最初にアプリを保護する*:復元する前に、アプリケーションのスナップショットを取るか、バックアップすることを強くお勧めします。リストアに失敗した場合に、Snapshotまたはバックアップからクローニングできます。
* *デスティネーションストレージクラスを確認*：別のクラスタにリストアする場合は、デスティネーションクラスタのストレージクラスがソースクラスタのストレージクラスと同じ永続ボリュームアクセスモード（ReadWriteManyなど）を使用していることを確認してください。デスティネーションの永続ボリュームアクセスモードが異なると、リストア処理は失敗します。


.手順
. 「 * アプリケーション」を選択し、アプリケーションの名前を選択します。
. 「 * データ保護 * 」を選択します。
. Snapshot からリストアする場合は、「 * Snapshot * 」を選択したままにします。それ以外の場合は、「 * Backups * 」を選択してバックアップからリストアします。
. リストア元のスナップショットまたはバックアップの [* アクション * ] 列の [ オプション ] メニューから、 [ * アプリケーションのリストア * ] を選択します。
. リストアタイプを選択します。
+
** *元のネームスペースにリストア*：この手順 を使用して、アプリケーションを元のクラスタにインプレースでリストアします。
+
[CAUTION]
====
リソースを共有するアプリケーションでIn Placeリストア処理を実行すると、予期しない結果が生じる可能性があります。アプリケーション間で共有されているリソースは、いずれかのアプリケーションでインプレースリストアが実行されると置き換えられます。

====
+
... アプリをインプレースで復元するために使用するスナップショットを選択します。これにより、アプリは以前のバージョンのに戻ります。
... 「 * 次へ * 」を選択します。
+

NOTE: 以前に削除したネームスペースにリストアすると、同じ名前の新しいネームスペースがリストアプロセスで作成されます。以前に削除したネームスペースでアプリケーションを管理する権限を持つユーザは、新しく作成したネームスペースに手動で権限を復元する必要があります。

... リストア操作の詳細を確認し、「restore」と入力して、「* Restore *」を選択します。


** *新しい名前空間に復元*：この手順 を使用して、アプリを別のクラスタまたはソースとは異なる名前空間で別のクラスタに復元します。
+
... リストアするアプリケーションのデスティネーションクラスタを選択します。
... アプリケーションに関連付けられている各ソースネームスペースのデスティネーションネームスペースを入力します。
+

NOTE: Astra Controlは、このリストアオプションの一部として新しいデスティネーションネームスペースを作成します。指定するデスティネーションネームスペースがデスティネーションクラスタに存在していないことを確認してください。

... 「 * 次へ * 」を選択します。
... アプリケーションのリストアに使用するスナップショットを選択します。
... 「 * 次へ * 」を選択します。
... リストア処理の詳細を確認し、* Restore *を選択します。






.結果
Astra Control は、指定した情報に基づいてアプリケーションを復元します。アプリケーションをインプレースでリストアした場合、既存の永続ボリュームのコンテンツが、リストアしたアプリケーションの永続ボリュームのコンテンツに置き換えられます。


NOTE: ネームスペースの名前/ IDまたはネームスペースのラベルでネームスペースの制約を受けているメンバーユーザは、同じクラスタの新しいネームスペース、または組織のアカウントに含まれる他のクラスタにアプリケーションをクローニングまたはリストアできます。ただし、同じユーザが、クローニングまたはリストアされたアプリケーションに新しいネームスペースからアクセスすることはできません。クローンまたはリストア処理によって新しいネームスペースが作成されると、アカウントの管理者 / 所有者はメンバーユーザアカウントを編集し、該当するユーザに新しいネームスペースへのアクセスを許可するロールの制限を更新できます。
