---
sidebar: sidebar 
permalink: use/set-up-billing.html 
keywords: billing, set up billing, payments, set up payments, credit card, update credit card, change credit card, free plan, free trial, premium, premium plan 
summary: Astra Control Serviceは、ネームスペースに対して2つの課金方法を提供します。フリープランを使用すると、アカウント内で最大10個のアプリを管理できます。10を超える名前空間を管理する場合は、無料プランからプレミアムプランにアップグレードして請求を設定する必要があります。または、AzureやAWS MarketplaceからAzureやAWSへの請求を管理することもできます。 
---
= 請求を設定します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
複数の方法でAstra Control Serviceアカウントの課金を管理できます。AzureまたはAmazon AWSを使用している場合は、Microsoft Azure MarketplaceまたはAWS MarketplaceからAstra Control Serviceプランに登録できます。これを行うと、Marketplaceで請求先の詳細を管理できます。または、ネットアップに直接登録することもできます。ネットアップに直接登録した場合は、Astra Control Serviceを使用して課金情報を管理できます。サブスクリプションなしでAstra Control Serviceを使用すると、自動的にFree Planに登録されます。

Astra Control Service Free Planでは、アカウント内のネームスペースを最大10個まで管理できます。10個を超えるネームスペースを管理する場合は、Free PlanからPremium Planにアップグレードするか、Azure MarketplaceまたはAWS Marketplaceでサブスクライブすることで請求を設定する必要があります。



== 課金の概要

Astra Control Service の使用には、ネットアップの Astra Control Service の料金と、永続的ボリュームとオブジェクトストレージをクラウドプロバイダから課金する、 2 種類のコストが関連します。



=== Astra Control サービスの請求

Astra Control Service には、次の 3 つのプランがあります。

自由な計画:: 最大10個のネームスペースを無料で管理できます。
Premium PayGo の場合:: ネームスペースを1つのネームスペースに対して1時間あたりの特定の割合で管理します。
プレミアムサブスクリプション:: ネームスペースパック_ごとに最大10個のネームスペースを管理できる年間サブスクリプションを使用して、割引価格で前払いします。ネットアップの営業担当に問い合わせて、必要なパックを購入してください。たとえば、30個のネームスペースを管理する3パックをAstra Control Serviceから購入します。年間サブスクリプションで許可されている数を超えるネームスペースを管理した場合は、追加のネームスペースごとのサブスクリプション依存の超過レートが課金されます。
+
--
まだ Astra Control アカウントをお持ちでない場合は、 Premium サブスクリプションを購入すると Astra Control アカウントが自動的に作成されます。既存の無料プランがある場合は、自動的に Premium サブスクリプションに変換されます。

--


Astra Controlアカウントを作成すると、自動的にFree Planに登録されます。Astra Controlのダッシュボードには、現在許可されている10個の空きネームスペースから管理しているネームスペースの数が表示されます。名前空間を含む最初のアプリケーションが管理されると、名前空間の請求が開始され、名前空間を含む最後のアプリケーションが管理されない場合は、その名前空間の請求が停止します。

11番目の名前空間を管理しようとすると、Astra ControlからFree Planの制限に達したことが通知されます。その後、フリープランからプレミアムプランへのアップグレードを求めるプロンプトが表示されます。追加のネームスペースごとに、サブスクリプションに応じた超過料金が発生します。

Premium プランにはいつでもアップグレードできます。アップグレード後、Astra Controlはアカウントの_ALL_Namespacesに課金します。最初の10個の名前空間は、フリープランに残りません。

ifdef::gcp[]



=== Google Cloud の請求

Astra Control Service を使用して GKE クラスタを管理する場合、永続ボリュームは NetApp Cloud Volumes Service によってバックアップされ、アプリのバックアップは Google Cloud Storage バケットに保存されます。

* https://["Cloud Volumes Service の価格設定の詳細を表示"^]。
+
Astra Control Service は、すべてのサービスタイプとサービスレベルをサポートします。使用するサービスタイプは、によって異なります https://["Google Cloud リージョン"^]。

* https://["Google Cloud ストレージバケットの価格設定の詳細を表示します"^]。


endif::gcp[]

ifdef::azure[]



=== Microsoft Azure 請求

AKS クラスタを Astra Control Service で管理する場合、永続ボリュームは Azure NetApp Files によってバックアップされ、アプリケーションのバックアップは Azure BLOB コンテナに格納されます。

* https://["Azure NetApp Files の価格設定の詳細を表示"^]。
* https://["Microsoft Azure BLOB ストレージの価格設定の詳細を表示する"^]。


endif::azure[]

ifdef::aws[]



=== Amazon Web Servicesの請求

Astra Control Serviceを使用してAWSクラスタを管理する場合、永続ボリュームはEBSまたはFSX for NetApp ONTAP でバックアップされ、アプリケーションのバックアップはAWSバケットに格納されます。

* https://["Amazon Web Servicesの価格設定の詳細を表示します"^]。


endif::aws[]



== Azure MarketplaceでAstra Control Serviceに登録

Azure Marketplaceを使用してAstra Control Serviceに登録することができます。アカウントと請求先の詳細は、Marketplaceで管理されます。


NOTE: Azure Marketplaceのサブスクリプションプロセスのデモビデオを見るには、を参照してください https://["ネットアップTV"^]。

.手順
. にアクセスします https://["Azure Marketplace で入手できます"^]。
. [*今すぐ取得*]を選択します。
. 指示に従って、プランをサブスクライブします。




== AWS MarketplaceでAstra Control Serviceに登録

AWS Marketplaceを使用してAstra Control Serviceに登録することができます。アカウントと請求先の詳細は、Marketplaceで管理されます。

.手順
. にアクセスします https://["AWS Marketplace"^]。
. [*購読を続行する*]を選択します。
. 指示に従って、プランをサブスクライブします。




== ネットアップのAstra Control Serviceに直接登録できます

Astra Control Serviceには、Astra Control Service UIから登録するか、ネットアップの営業にお問い合わせください。



=== 無料プランから Premium PayGo プランへのアップグレード

支払いプランをいつでもアップグレードして、必要に応じて料金を支払うことで、Astra Controlから10を超える名前空間の管理を開始できます。必要なのは有効なクレジットカードだけです。

.手順
. [*Account] を選択し、 [*Billing *] を選択します。
. [* プラン * ] で、 [* Premium PayGo* ] に移動し、 [* 今すぐアップグレード * ] を選択します。
. 有効なクレジットカードの支払い情報を入力して、「プレミアムプランへのアップグレード」を選択します。
+

NOTE: クレジットカードの有効期限が近づいている場合は、 Astra Control から電子メールでお知らせします。



.結果
10個を超えるネームスペースを管理できるようになりました。Astra Controlは、現在管理している_All_Namespacesの課金を開始します。



=== 無料プランからプレミアムサブスクリプションへのアップグレード

ネットアップの営業担当に問い合わせて、年単位のサブスクリプション料金が割引価格で前払いされていることを確認してください。

.手順
. [*Account] を選択し、 [*Billing *] を選択します。
. [* プラン * ] で、 [* プレミアムサブスクリプション * ] に移動し、 [* セールスへのお問い合わせ ] を選択します。
. プロセスを開始するための詳細を営業チームに入力します。


.結果
発注プロセスを進める際には、ネットアップの営業担当者からご連絡いたします。注文が完了すると、Astra Controlは、*Billing *タブで現在の計画を反映します。



== 現在のコストと請求履歴を表示します

Astra Controlでは、現在の月単位のコストと、名前空間ごとの詳細な請求履歴が表示されます。Marketplaceでプランに登録した場合、請求履歴は表示されません（Marketplaceにログインすると表示できます）。

.手順
. [*Account] を選択し、 [*Billing *] を選択します。
+
現在のコストは、課金の概要の下に表示されます。

. 名前空間ごとに請求履歴を表示するには、[請求履歴*]を選択します。
+
Astra Controlを使用すると、各ネームスペースの使用量とコストを分単位で表示できます。使用分は、課金期間中にAstra Controlが名前空間を管理した分数です。

. ドロップダウンリストを選択して前の月を選択します。




== Premium PayGo のクレジットカードを変更します

必要に応じて、支払い用に Astra Control のクレジットカードをファイルに変更できます。

.手順
. ［ * アカウント ］ > ［ 請求 ］ > ［ 支払方法 * ］ の順に選択します。
. 設定アイコンを選択します。
. クレジットカードを変更します。




== 重要事項

* 請求計画は Astra Control アカウントごとに作成します。
+
アカウントが複数ある場合は、それぞれに独自の課金プランがあります。

* Astra Controlの料金には、名前空間を管理するための料金が含まれています。ストレージバックエンドの永続ボリュームに対して、クラウドプロバイダが別途料金を請求します。
+
link:../get-started/intro.html["Astra Control の価格設定の詳細"]。

* 各請求期間は、その月の最終日に終了します。
* プレミアムプランからフリープランにダウングレードすることはできません。

