---
sidebar: sidebar 
permalink: use/set-up-billing.html 
keywords: billing, set up billing, payments, set up payments, credit card, update credit card, change credit card, free plan, free trial, premium, premium plan 
summary: Astra Control の無料プランを使用すると、最大 10 個のアプリをアカウントで管理できます。10 以上のアプリを管理する場合は、無料プランからプレミアムプランにアップグレードして請求を設定する必要があります。 
---
= 請求を設定します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Astra Control の無料プランを使用すると、最大 10 個のアプリをアカウントで管理できます。10 以上のアプリを管理する場合は、無料プランからプレミアムプランにアップグレードして請求を設定する必要があります。



== 課金の概要

Astra Control Service の使用には、ネットアップの Astra Control Service の料金と、永続的ボリュームとオブジェクトストレージをクラウドプロバイダから課金する、 2 種類のコストが関連します。



=== Astra Control サービスの請求

Astra Control Service には、次の 3 つのプランがあります。

自由な計画:: 最大 10 個のアプリを無料で管理できます。
Premium PayGo の場合:: アプリごとに 1 分あたり $0.005 の割合で、無制限のアプリを管理します。
プレミアムサブスクリプション:: アプリケーションパック _ ごとに最大 10 個のアプリケーションを管理できる年間サブスクリプションを使用して、割引価格で前払いします。ネットアップの営業担当に問い合わせて、組織に必要なパックをいくつでも購入してください。たとえば、 Astra Control Service から 30 個のアプリケーションを管理するために 3 パックを購入します。年間サブスクリプションで許可されている数を超えるアプリを管理した場合、アプリケーションごとに 1 分あたり 0.005 ドルの超過レート（ Premium PayGo と同じ）が課金されます。
+
--
まだ Astra Control アカウントをお持ちでない場合は、 Premium サブスクリプションを購入すると Astra Control アカウントが自動的に作成されます。既存の無料プランがある場合は、自動的に Premium サブスクリプションに変換されます。

--


Astra Control アカウントを作成すると、無料プランに自動的にサインアップされます。Astra Control のダッシュボードには、現在管理している 10 個の無料アプリのうち、許可されているものをいくつ管理しているかが表示されます。

11 番目のアプリを管理しようとすると、 Astra Control から無料プランの制限に達したことが通知されます。その後、フリープランからプレミアムプランへのアップグレードを求めるプロンプトが表示されます。

Premium プランにはいつでもアップグレードできます。アップグレード後、アカウントの _all_managed アプリの料金が Astra Control によって請求されます。最初の 10 個のアプリは、無料プランには含まれていません。

ifdef::gcp[]



=== Google Cloud の請求

Astra Control Service を使用して GKE クラスタを管理する場合、永続ボリュームは NetApp Cloud Volumes Service によってバックアップされ、アプリのバックアップは Google Cloud Storage バケットに保存されます。

* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/costs["Cloud Volumes Service の価格設定の詳細を表示"^]。
+
Astra Control Service は、すべてのサービスタイプとサービスレベルをサポートします。使用するサービスタイプは、によって異なります https://cloud.netapp.com/cloud-volumes-global-regions#cvsGcp["Google Cloud リージョン"^]。

* https://cloud.google.com/storage/pricing["Google Cloud ストレージバケットの価格設定の詳細を表示します"^]。


endif::gcp[]

ifdef::azure[]



=== Microsoft Azure 請求

AKS クラスタを Astra Control Service で管理する場合、永続ボリュームは Azure NetApp Files によってバックアップされ、アプリケーションのバックアップは Azure BLOB コンテナに格納されます。

* https://azure.microsoft.com/en-us/pricing/details/netapp["Azure NetApp Files の価格設定の詳細を表示"^]。
* https://azure.microsoft.com/en-us/pricing/details/storage/blobs["Microsoft Azure BLOB ストレージの価格設定の詳細を表示する"^]。


endif::azure[]



== 重要事項

* 請求計画は Astra Control アカウントごとに作成します。
+
アカウントが複数ある場合は、それぞれに独自の課金プランがあります。

* Astra Control の料金には、 Kubernetes アプリケーションの管理費用が含まれています。永続ボリュームのストレージバックエンド用に、クラウドプロバイダから別途料金が請求されます。
+
link:../get-started/intro.html["Astra Control の価格設定の詳細"]。

* 各請求期間は、その月の最終日に終了します。
* プレミアムプランからフリープランにダウングレードすることはできません。




== 無料プランから Premium PayGo プランへのアップグレード

支払いプランをいつでもアップグレードして、必要に応じて料金を支払うことで、 Astra Control から 10 以上のアプリの管理を開始できます。必要なのは有効なクレジットカードだけです。

.手順
. [*Account] を選択し、 [*Billing *] を選択します。
. [* プラン * ] で、 [* Premium PayGo* ] に移動し、 [* 今すぐアップグレード * ] を選択します。
. 有効なクレジットカードの支払い情報を入力して、「プレミアムプランへのアップグレード」を選択します。
+

NOTE: クレジットカードの有効期限が近づいている場合は、 Astra Control から電子メールでお知らせします。



10 以上のアプリを管理できるようになりました。Astra Control は、現在管理している _ALL_APPS の課金を開始します。



== 無料プランからプレミアムサブスクリプションへのアップグレード

ネットアップの営業担当に問い合わせて、年単位のサブスクリプション料金が割引価格で前払いされていることを確認してください。

.手順
. [*Account] を選択し、 [*Billing *] を選択します。
. [* プラン * ] で、 [* プレミアムサブスクリプション * ] に移動し、 [* セールスへのお問い合わせ ] を選択します。
. プロセスを開始するための詳細を営業チームに入力します。


発注プロセスを進める際には、ネットアップの営業担当者からご連絡いたします。注文が完了すると、 Astra Control は請求タブに現在の計画を反映します。



== 現在のコストと請求履歴を表示します

Astra Control には、現在の月単位のコストと、アプリケーションごとの詳細な請求履歴が表示されます。

.手順
. [*Account] を選択し、 [*Billing *] を選択します。
+
現在のコストは、課金の概要の下に表示されます。

. アプリで請求履歴を表示するには、「請求履歴」を選択します。
+
Astra Control を使用すると、各アプリケーションの使用時間とコストを分単位で表示できます。使用分は、課金期間中に Astra Control がアプリケーションを管理した分数です。

. ドロップダウンリストを選択して前の月を選択します。




== Premium PayGo のクレジットカードを変更します

必要に応じて、支払い用に Astra Control のクレジットカードをファイルに変更できます。

.手順
. ［ * アカウント ］ > ［ 請求 ］ > ［ 支払方法 * ］ の順に選択します。
. 設定アイコンを選択します。
. クレジットカードを変更します。

