---
sidebar: sidebar 
permalink: use/unmanage.html 
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster 
summary: 管理する必要がなくなったアプリケーションやクラスタを Astra Control から削除 
---
= アプリケーションとクラスタの管理を解除します
:hardbreaks:
:icons: font
:imagesdir: ../media/use/


管理する必要がなくなったアプリケーションやクラスタを Astra Control から削除



== アプリの管理を停止します

バックアップ、スナップショット、またはクローンを作成する必要がなくなったアプリケーションの管理を Astra Control から停止します。

* 既存のバックアップと Snapshot がすべて削除されます。
* アプリケーションとデータは引き続き使用できます。


.手順
. 「 * アプリケーション * 」を選択します。
. 管理する必要がなくなったアプリのチェックボックスをオンにします。
. [* アクション * （ * Action * ） ] ドロップダウンを選択し、 [ * アプリケーションの管理解除 * （ Unmanage application/s * ） ] を選択します。
. アプリの管理を解除することを確認し、 [ はい ] 、 [ アプリケーションの管理を解除 ] を選択します。


Astra Control がアプリケーションの管理を停止。



== クラスタの管理を停止します

管理する必要がなくなったクラスタを Astra Control から管理しないようにします。ベストプラクティスとして、 GCP からクラスタを削除する前に、 Astra Control からクラスタを削除することを推奨します。

* この操作を実行すると、 Astra Control でクラスタが管理されなくなります。クラスタの構成は変更されず、クラスタも削除されません。
* Astra Trident はクラスタからアンインストールされません。 https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Astra Trident のアンインストール方法をご確認ください"^]。


.手順
. 「 * クラスタ * 」を選択します。
. 管理する必要がなくなったクラスタのチェックボックスを選択します。
. [* アクション * （ Actions * ） ] ドロップダウンを選択し、 [ * 管理解除 * （ Unmanage * ） ] を選択します
. クラスタの管理を解除することを確認し、「 * Yes 、 Unmanage cluster * 」を選択します。


Astra Control がクラスタの管理を停止。



== クラウドプロバイダからクラスタを削除しています

ネットアップストレージクラスに永続ボリューム（ PV ）が存在する Kubernetes クラスタを削除する前に、次のいずれかの方法で永続ボリューム要求（ PVC ）を削除する必要があります。クラスタを削除する前に PVC と PV を削除すると、クラウドプロバイダから予期しない請求書が届かなくなります。

* * 方法 1 * ：アプリケーションワークロードのネームスペースをクラスタから削除します。Trident ネームスペースを削除しないでください。
* * 方法 #2 * ： PVC とポッド、または PVS がマウントされている配置を削除します。


Kubernetes クラスタを Astra Control から管理する場合、そのクラスタ上のアプリケーションは、永続的ボリュームのストレージバックエンドとして Cloud Volumes Service または Azure NetApp Files を使用します。事前に PVS を削除せずにクラウドプロバイダからクラスタを削除した場合、バックエンドボリュームはクラスタと一緒に _not_deleted になります。

上記のいずれかの方法を使用すると、対応する PVS がクラスタから削除されます。クラスタを削除する前に、クラスタのネットアップストレージクラスに PVS が存在していないことを確認してください。

クラスタを削除する前に永続ボリュームを削除していない場合は、 Cloud Volumes Service for Google Cloud または Azure NetApp Files からバックエンドボリュームを手動で削除する必要があります。
