---
sidebar: sidebar 
permalink: use/unmanage.html 
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster 
summary: 管理する必要がなくなったアプリケーションやクラスタを Astra Control から削除 
---
= アプリケーションとクラスタの管理を解除します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
管理する必要がなくなったアプリケーションやクラスタを Astra Control から削除



== アプリの管理を停止します

バックアップ、スナップショット、またはクローンを作成する必要がなくなったアプリケーションの管理を Astra Control から停止します。

アプリケーションの管理を解除すると、次のようになります。

* 既存のバックアップと Snapshot がすべて削除されます。
* アプリケーションとデータは引き続き使用できます。


.手順
. 左側のナビゲーションバーから、「 * アプリケーション * 」を選択します。
. アプリケーションを選択します。
. [アクション]列の[オプション]メニューから、*Unmanage*を選択します。
. 情報を確認します。
. 「 unmanage 」と入力して確定します。
. [ はい、アプリケーションの管理を解除 * ] を選択します。


.結果
Astra Control がアプリケーションの管理を停止。



== クラスタの管理を停止します

管理する必要がなくなったクラスタを Astra Control から管理しないようにします。

ifdef::gcp[]


NOTE: クラスタの管理を解除する前に、クラスタに関連付けられているアプリケーションの管理を解除する必要があります。

ベストプラクティスとして、 GCP からクラスタを削除する前に、 Astra Control からクラスタを削除することを推奨します。

endif::gcp[]

クラスタの管理を解除する場合：

* この操作を実行すると、 Astra Control でクラスタが管理されなくなります。クラスタの構成は変更されず、クラスタも削除されません。
* Astra Trident はクラスタからアンインストールされません。 https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Astra Trident のアンインストール方法をご確認ください"^]。


.手順
. 「 * クラスタ * 」を選択します。
. 管理する必要がなくなったクラスタのチェックボックスを選択します。
. * アクション * 列のオプションメニューから、 * 管理解除 * を選択します。
. クラスタの管理を解除することを確認し、「 * Yes 、 unmanage cluster * 」を選択します。


.結果
クラスタのステータスが「Removing *」に変わります。その後、クラスタが「*クラスタ」ページから削除され、Astra Control Centerによって管理されなくなります。



== クラウドプロバイダからクラスタを削除しています

ネットアップストレージクラスに永続ボリューム（ PV ）が存在する Kubernetes クラスタを削除する前に、次のいずれかの方法で永続ボリューム要求（ PVC ）を削除する必要があります。クラスタを削除する前に PVC と PV を削除すると、クラウドプロバイダから予期しない請求書が届かなくなります。

* * 方法 1 * ：アプリケーションワークロードのネームスペースをクラスタから削除します。Trident ネームスペースを削除しないでください。
* * 方法 #2 * ： PVC とポッド、または PVS がマウントされている配置を削除します。


KubernetesクラスタをAstra Controlから管理する場合、そのクラスタ上のアプリケーションは、永続的ボリュームのストレージバックエンドとしてクラウドプロバイダを使用します。事前に PVS を削除せずにクラウドプロバイダからクラスタを削除した場合、バックエンドボリュームはクラスタと一緒に _not_deleted になります。

上記のいずれかの方法を使用すると、対応する PVS がクラスタから削除されます。クラスタを削除する前に、クラスタのネットアップストレージクラスに PVS が存在していないことを確認してください。

クラスタを削除する前に永続ボリュームを削除していない場合は、クラウドプロバイダからバックエンドボリュームを手動で削除する必要があります。
