---
sidebar: sidebar 
permalink: get-started/add-private-provider-managed-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 環境のセットアップが完了したら、 Kubernetes クラスタを作成し、 Astra Control Service に追加することができます。 
---
= プロバイダが管理するプライベートクラスタをAstra Control Serviceに追加します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Serviceを使用して、Google Kubernetes Engine（GKE）のプライベートクラスタを管理できます。ここでは、プライベートAKSまたはOpenShiftクラスタがすでに作成されており、リモートからアクセスするための安全な方法が用意されていることを前提としています。プライベートAKSまたはOpenShiftクラスタの作成とアクセスの詳細については、次のドキュメントを参照してください。

* https://docs.microsoft.com/azure/aks/private-clusters["プライベートAKSクラスタに関するAzureのドキュメント"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["プライベートOpenShiftクラスタに関するAzureのドキュメント"^]


Astra Control Serviceを使用して、AKSでプライベートAzure Kubernetes Service（AKS）クラスタとプライベートRed Hat OpenShiftクラスタを管理できます。ここでは、プライベートAKSまたはOpenShiftクラスタがすでに作成されており、リモートからアクセスするための安全な方法が用意されていることを前提としています。プライベートAKSまたはOpenShiftクラスタの作成とアクセスの詳細については、次のドキュメントを参照してください。

* https://docs.microsoft.com/azure/aks/private-clusters["プライベートAKSクラスタに関するAzureのドキュメント"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["プライベートOpenShiftクラスタに関するAzureのドキュメント"^]


Astra Control Serviceを使用して、プライベートAmazon Elastic Kubernetes Service（EKS）クラスタを管理できます。ここで説明する手順では、プライベートEKSクラスタがすでに作成されており、リモートからアクセスするためのセキュアな方法が用意されていることを前提としています。プライベートEKSクラスタの作成とアクセスの詳細については、を参照してください https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html["Amazon EKSのドキュメント"^]。

Astra Control Serviceにプライベートクラスタを追加するには、次のタスクを実行する必要があります。

. <<Astra Connectorのインストール>>
. <<永続的ストレージをセットアップする>>
. <<プロバイダが管理するプライベートクラスタをAstra Control Serviceに追加>>




== Astra Connectorのインストール

プライベートクラスタを追加する前に、Astra Controlがクラスタと通信できるように、クラスタにAstra Connectorをインストールする必要があります。を参照してください link:install-astra-connector.html["プライベートクラスタ用のAstra Connectorのインストール"] 手順については、を参照し



== 永続的ストレージをセットアップする

クラスタに永続的ストレージを設定してください。永続的ストレージの設定の詳細については、『Get Started』ドキュメントを参照してください。

ifdef::azure[]

* link:set-up-microsoft-azure-with-anf.html["Azure NetApp Files を使用して Microsoft Azure をセットアップする"^]
* link:set-up-microsoft-azure-with-amd.html["Azure で管理されているディスクを使用して Microsoft Azure をセットアップする"^]


endif::azure[]

ifdef::aws[]

* link:set-up-amazon-web-services.html["Amazon Web Servicesをセットアップする"^]


endif::aws[]

ifdef::gcp[]

* link:set-up-google-cloud.html["Google Cloud をセットアップします"^]


endif::gcp[]



== プロバイダが管理するプライベートクラスタをAstra Control Serviceに追加

プライベートクラスタをAstra Control Serviceに追加できるようになりました。

Azure Kubernetes ServiceクラスタとGoogle Kubernetes Engineクラスタを管理する場合、Astra Control Provisionerのインストールとライフサイクル管理には次の2つのオプションがあることに注意してください。

* Astra Control Serviceを使用すると、Astra Control Provisionerのライフサイクルを自動的に管理できます。そのためには、Astra Control Serviceで管理するクラスタでAstra Tridentがインストールされておらず、Astra Control Provisionerが有効になっていないことを確認してください。この場合、クラスタの管理を開始すると、Astra Control ServiceによってAstra Control Provisionerが自動的に有効になり、Astra Control Provisionerのアップグレードは自動的に処理されます。
* Astra Control Provisionerのライフサイクルは自分で管理できます。これを行うには、Astra Control Serviceでクラスタを管理する前に、クラスタでAstra Control Provisionerを有効にします。この場合、Astra Control ServiceはAstra Control Provisionerがすでに有効になっていることを検出し、再インストールやAstra Control Provisionerのアップグレードの管理は行いません。を参照してください link:../use/enable-acp.html["Astra Control Provisionerを有効にする"^] では、Astra Control Provisionerを有効にします。


Astra Control ServiceでAmazon Web Servicesクラスタを管理する場合、Astra Control Provisionerでのみ使用できるストレージバックエンドが必要な場合は、Astra Control Serviceで管理する前に、クラスタでAstra Control Provisionerを手動で有効にする必要があります。を参照してください link:../use/enable-acp.html["Astra Control Provisionerを有効にする"^] をクリックし、Astra Control Provisionerを有効にします。

.作業を開始する前に
[%collapsible%open]
====
ifdef::aws[]

.Amazon Web Services の
* クラスタを作成したIAMユーザのクレデンシャルを含むJSONファイルが必要です。 link:../get-started/set-up-amazon-web-services.html#create-an-iam-user["IAMユーザを作成する方法を説明します"]。
* Amazon FSx for NetApp ONTAPにはAstra Controlプロビジョニングツールが必要です。EKSクラスタのストレージバックエンドとしてAmazon FSx for NetApp ONTAPを使用する予定の場合は、 link:set-up-amazon-web-services.html#eks-cluster-requirements["EKSクラスタ要件"]。
* （オプション）を指定する必要がある場合 `kubectl` クラスタの作成者ではない他のIAMユーザにクラスタをアクセスするためのコマンドアクセスについては、の手順を参照してください https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/["Amazon EKSでクラスタを作成したあと、他のIAMユーザとロールにアクセスを提供するにはどうすればよいですか？"^]。
* NetApp Cloud Volumes ONTAP をストレージバックエンドとして使用する場合は、Amazon Web Servicesと連携するようにCloud Volumes ONTAP を設定する必要があります。Cloud Volumes ONTAP を参照してください https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["セットアップのドキュメント"^]。


endif::aws[]

ifdef::azure[]

.Microsoft Azure
* サービスプリンシパルの作成時に、Azure CLIからの出力を含むJSONファイルが必要です。 link:../get-started/set-up-microsoft-azure-with-anf.html#create-an-azure-service-principal-2["サービスプリンシパルの設定方法について説明します"]。
+
JSON ファイルに追加していない場合は、 Azure サブスクリプション ID も必要になります。



* NetApp Cloud Volumes ONTAP をストレージバックエンドとして使用する場合は、Microsoft Azureと連携するようにCloud Volumes ONTAP を設定する必要があります。Cloud Volumes ONTAP を参照してください https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["セットアップのドキュメント"^]。


endif::azure[]

ifdef::gcp[]

.Google Cloud
* 必要な権限を持つサービスアカウントのサービスアカウントキーファイルが必要です。 link:../get-started/set-up-google-cloud.html#create-a-service-account["サービスアカウントの設定方法について説明します"]。
* クラスタがプライベートの場合は、を参照してください https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept["許可されたネットワーク"^] Astra Control Service の IP アドレスを許可する必要があります。
+
52.188.218.166-32

* NetApp Cloud Volumes ONTAP をストレージバックエンドとして使用する場合は、Google Cloudと連携するようにCloud Volumes ONTAP を設定する必要があります。Cloud Volumes ONTAP を参照してください https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["セットアップのドキュメント"^]。


endif::gcp[]

====
.手順
. （オプション）Amazon EKSクラスタを追加する場合、またはAstra Control Provisionerのインストールとアップグレードを自分で管理する場合は、クラスタでAstra Control Provisionerを有効にします。を参照してください link:../use/enable-acp.html["Astra Control Provisionerを有効にする"^] を参照してください。
. ブラウザでAstra Control Service Web UIを開きます。
. ダッシュボードで、 * Kubernetes クラスタの管理 * を選択します。
+
プロンプトに従ってクラスタを追加します。

. *プロバイダ*：クラウドプロバイダを選択し、新しいクラウドインスタンスを作成するために必要なクレデンシャルを入力するか、使用する既存のクラウドインスタンスを選択します。


ifdef::aws[]

. * Amazon Web Services *：JSONファイルをアップロードするか、クリップボードからそのJSONファイルの内容を貼り付けて、Amazon Web Services IAMユーザアカウントの詳細を指定します。
+
JSONファイルに、クラスタを作成したIAMユーザのクレデンシャルを含める必要があります。



endif::aws[]

ifdef::azure[]

. * Microsoft Azure * ： JSON ファイルをアップロードするか、クリップボードからその JSON ファイルの内容を貼り付けて、 Azure サービスプリンシパルの詳細を指定します。
+
JSON ファイルに、サービスプリンシパルの作成時に Azure CLI からの出力が含まれている必要があります。サブスクリプション ID を含めることで、 Astra に自動的に追加されるようにすることもできます。ID が必要な場合は、 JSON の指定後に手動で ID を入力する必要があります。



endif::azure[]

ifdef::gcp[]

. * Google Cloud Platform * ：ファイルをアップロードするか、クリップボードからコンテンツを貼り付けて、サービスアカウントのキーファイルを提供します。
+
Astra Control Service は、サービスアカウントを使用して、 Google Kubernetes Engine で実行されているクラスタを検出します。



endif::gcp[]

. *その他*：このタブは自己管理クラスタでのみ使用できます。
+
.. *クラウドインスタンス名*：このクラスタを追加するときに作成される新しいクラウドインスタンスの名前を指定します。の詳細を確認してください link:../use/manage-cloud-instances.html["クラウドインスタンス"]。
.. 「 * 次へ * 」を選択します。
+
Astra Control Serviceに、クラスタのリストが表示されます。

.. *クラスタ*：Astra Control Serviceに追加するクラスタをリストから選択します。
+

NOTE: クラスタのリストから選択する場合は、* Eligiblity *列に注意してください。クラスタが「ineligible」または「partially eligible」の場合は、ステータスにカーソルを合わせて、そのクラスタに問題があるかどうかを確認します。たとえば、クラスタにワーカーノードがないことがわかります。





. 「 * 次へ * 」を選択します。
. （オプション）* Storage *：必要に応じて、このクラスタに導入されたKubernetesアプリケーションでデフォルトで使用するストレージクラスを選択します。
+
.. クラスタの新しいデフォルトのストレージクラスを選択するには、*[新しいデフォルトのストレージクラスを割り当てる]*チェックボックスを有効にします。
.. 新しいデフォルトのストレージクラスをリストから選択します。
+
[NOTE]
====
各クラウドプロバイダのストレージサービスには、コスト、パフォーマンス、耐障害性に関する次の情報が表示されます。

ifdef::gcp[]

*** Cloud Volumes Service for Google Cloud：価格、パフォーマンス、耐障害性に関する情報
*** Google Persistent Disk：コスト、パフォーマンス、耐障害性に関する情報は提供されません


endif::gcp[]

ifdef::azure[]

*** Azure NetApp Files ：パフォーマンスと耐障害性に関する情報
*** Azure Managed Disks：価格、パフォーマンス、耐障害性に関する情報は提供されません


endif::azure[]

ifdef::aws[]

*** Amazon Elastic Block Store：価格、パフォーマンス、耐障害性に関する情報がない
*** Amazon FSX for NetApp ONTAP ：価格、パフォーマンス、耐障害性に関する情報は提供されません


endif::aws[]

*** NetApp Cloud Volumes ONTAP ：価格、パフォーマンス、耐障害性に関する情報は提供されません


====
+
ストレージクラスごとに、次のいずれかのサービスを利用できます。





ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service for Google Cloud"^]
* https://cloud.google.com/persistent-disk/["Google Persistent Disk のことです"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files の特長"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Azure で管理されるディスク"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP 対応の Amazon FSX"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["NetApp Cloud Volumes ONTAP の略"^]
+
の詳細を確認してください link:../learn/aws-storage.html["Amazon Web Servicesクラスタのストレージクラス"]。の詳細を確認してください link:../learn/azure-storage.html["AKS クラスタのストレージクラス"]。の詳細を確認してください link:../learn/choose-class-and-size.html["GKE クラスタのストレージクラス"]。

+
.. 「 * 次へ * 」を選択します。
.. *確認と承認*：構成の詳細を確認します。
.. [Add]*を選択して、Astra Control Serviceにクラスタを追加します。




.結果
このクラウドプロバイダ用に最初に追加したクラスタである場合、Astra Control Serviceは、対象となるクラスタで実行されているアプリケーションのバックアップ用に、クラウドプロバイダ用のオブジェクトストアを作成します。（このクラウドプロバイダに対して後続のクラスタを追加した場合、オブジェクトストアは作成されません）。デフォルトのストレージクラスを指定した場合は、指定したデフォルトのストレージクラスがAstra Control Serviceによって設定されます。Amazon Web ServicesまたはGoogle Cloud Platformで管理されるクラスタの場合、Astra Control Serviceはクラスタにも管理者アカウントを作成します。この処理には数分かかることがあります。



== デフォルトのストレージクラスを変更する

クラスタのデフォルトのストレージクラスは変更できます。



=== Astra Controlを使用してデフォルトのストレージクラスを変更する

クラスタのデフォルトのストレージクラスは、Astra Control内から変更できます。以前にインストールしたストレージバックエンドサービスをクラスタで使用している場合は、このメソッドを使用してデフォルトのストレージクラスを変更できない可能性があります（*デフォルトに設定*アクションは選択できません）。この場合は、を実行できます <<コマンドラインを使用してデフォルトのストレージクラスを変更します>>。

.手順
. Astra Control Service UI で、 [* Clusters] を選択します。
. [* Clusters]ページで、変更するクラスタを選択します。
. [ * ストレージ * ] タブを選択します。
. 「*ストレージクラス*」カテゴリを選択します。
. デフォルトとして設定するストレージクラスの* Actions *メニューを選択します。
. 「*デフォルトに設定*」を選択します。




=== コマンドラインを使用してデフォルトのストレージクラスを変更します

Kubernetesコマンドを使用してクラスタのデフォルトのストレージクラスを変更することができます。この方法は、クラスタの構成に関係なく機能します。

.手順
. Kubernetesクラスタにログインします。
. クラスタ内のストレージクラスを表示します。
+
[source, console]
----
kubectl get storageclass
----
. デフォルトのストレージクラスからデフォルトの指定を削除する。<SC_NAME> をストレージクラスの名前に置き換えます。
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. 別のストレージクラスをデフォルトとしてマークします。<SC_NAME> をストレージクラスの名前に置き換えます。
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. 新しいデフォルトストレージクラスを確認します。
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]
