---
sidebar: sidebar 
permalink: get-started/check-astra-trident-version.html 
keywords: astra trident, check, version, astra control provisioner 
summary: 自己管理型クラスタの場合は、正しいバージョンのAstra Tridentを使用していることを確認する必要があります。 
---
= Astra Tridentのバージョンを確認
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
ストレージサービスにAstra Control ProvisionerまたはAstra Tridentを使用する自己管理型クラスタを追加するには、Astra Tridentのバージョンが23.10以降であることを確認してください。

.手順
. 実行しているAstra Tridentのバージョンを確認します。
+
[source, console]
----
kubectl get tridentversions -n trident
----
+
Astra Tridentがインストールされている場合は、次のような出力が表示されます。

+
[listing]
----
NAME      VERSION
trident   24.02.0
----
+
Astra Tridentがインストールされていない場合は、次のような出力が表示されます。

+
[listing]
----
error: the server doesn't have a resource type "tridentversions"
----
. 次のいずれかを実行します。
+
** Astra Trident 23.01以前を実行している場合は、以下を使用 https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html["手順"^] Astra Control Provisionerにアップグレードする前に、Astra Tridentの最新バージョンにアップグレードすること。可能です link:../use/enable-acp.html["直接アップグレードを実行する"] Astra Tridentがバージョン24.02の4リリース期間内にある場合は、Astra Control Provisioner 24.02をダウンロードします。たとえば、Astra Trident 23.04からAstra Control Provisioner 24.02に直接アップグレードできます。
** Astra Trident 23.10以降を実行している場合は、Astra Control Provisionerが link:../use/faq.html#running-acp-check["有効"]。Astra Control Provisionerは、23.10より前のリリースのAstra Control Centerでは機能しません。 link:../get-started/enable-acp.html["Astra Control Provisionerのアップグレード"] 最新の機能にアクセスするには、アップグレードするAstra Control Centerと同じバージョンを使用する必要があります。


. ポッドが実行されていることを確認します。
+
[source, console]
----
kubectl get pods -n trident
----
. サポートされているAstra Tridentドライバをストレージクラスで使用しているかどうかを確認します。プロビジョニング担当者の名前はとします `csi.trident.netapp.io`。次の例を参照してください。
+
[source, console]
----
kubectl get sc
----
+
回答例：

+
[listing]
----
NAME                   PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ontap-gold (default)   csi.trident.netapp.io          Delete          Immediate           true                   5d23h
----

