---
sidebar: sidebar 
permalink: get-started/faq.html 
keywords: faq, frequently asked questions 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= Astra Control Service に関するよくある質問
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== 概要

Astra Control は、 Kubernetes ネイティブアプリケーション向けのアプリケーションデータのライフサイクル管理処理を簡易化します。Astra Control Serviceは、複数のクラウドプロバイダ環境で実行されるKubernetesクラスタをサポートします。

次のセクションでは、 Astra Control の使用時に表示される可能性のあるその他の質問に対する回答を示します。その他の説明については、 astra.feedback@netapp.com までお問い合わせください



== Astra Control へのアクセス

* Astra Control に登録する際に、詳細を入力する必要があるのはなぜですか。 *

Astra Control を登録する際には、正確な顧客情報が必要です。この情報は、 Global Trade Compliance (GTC) チェックを行うために必要です。

* Astra Control 登録時に「 Registration Failed 」エラーが表示されるのはなぜですか。 *

Astra Control では、お客様に正確な顧客情報を提供することがオンボーディングセクションで求められています。誤った情報を指定すると、「 Registration Failed 」エラーが表示されます。自分が所属している他のアカウントもロックされます。

* Astra Control Service の URL は何であるか。 *

Astra Control Service にはからアクセスできます https://astra.netapp.io[]。

* 同僚に電子メールの招待状を送信しましたが、受信していません。どうすればよいですか？ *

スパムフォルダで do-not-reply@netapp.com からの電子メールを確認するか、受信トレイで「招待」を検索するように依頼します。 また、ユーザを削除して、再度追加することもできます。

* 私は自由な計画からの Premium PayGO の計画にアップグレードした。最初の 10 個のアプリケーションに料金がかかりますか。 *

はい。Premium プランにアップグレードすると、アカウント内のすべての管理対象アプリケーションの料金が Astra Control から請求されます。

* 月中旬に Premium PayGO プランにアップグレードしました。月中は請求されますか？ *

いいえ。請求は、プレミアムプランにアップグレードした時点から開始されます。

* 無料プランを使用していますが、永続的ボリュームの請求には課金されますか？ *

はい、クラウドプロバイダからクラスタで使用される永続的ボリュームの料金が発生します。



== Kubernetes クラスタを登録しています

* CSI ドライバを Astra Control Service に追加する前に、 CSI ドライバをクラスタにインストールする必要がありますか。 *

いいえクラスターが Astra Control に追加されると、 NetApp Trident Container Storage Interface （ CSI ）ドライバが Kubernetes クラスタに自動的にインストールされます。このCSIドライバは、クラウドプロバイダによってサポートされているクラスタの永続ボリュームをプロビジョニングするために使用されます。

* Astra Control Service に追加した後、ワーカーノードをクラスタに追加する必要があります。どうすればよいですか？ *

新しいワーカーノードを既存のプールに追加することも、 Ubuntu イメージタイプであれば新しいプールを作成することもできます。これらは Astra Control によって自動的に検出されます。新しいノードが Astra Control に表示されない場合は、新しいワーカーノードでサポートされているイメージタイプが実行されているかどうかを確認します。kubectl get nodes コマンドを使用して ' 新しいワーカー・ノードの正常性を確認することもできます

ifdef::aws[]



== Elastic Kubernetes Service（EKS）クラスタを登録しています

* Astra Control ServiceにプライベートEKSクラスタを追加できますか。*

現時点では、Astra Control ServiceでプライベートEKSクラスタはサポートされていません。

endif::aws[]

ifdef::azure[]



== Azure Kubernetes Service（AKS）クラスタの登録

* AKS のプライベートクラスタを Astra Control Service に追加できますか。 *

はい、 AKS のプライベートクラスタを Astra 制御サービスに追加できます。プライベート AKS クラスタを追加するには、を参照してください link:add-first-cluster.html["Astra Control Service から Kubernetes クラスタの管理を開始します"]。

* Active Directoryを使用してAKSクラスタの認証を管理できますか。*

はい。認証とID管理にAzure Active Directory（Azure AD）を使用するようにAKSクラスタを設定できます。クラスタを作成するときは、の手順に従ってください https://docs.microsoft.com/en-us/azure/aks/managed-aad["公式ドキュメント"^] をクリックして、Azure ADを使用するようにクラスタを設定してください。AKSで管理されるAzure AD統合の要件をクラスタが満たしていることを確認する必要があります。

endif::azure[]

ifdef::gcp[]



== Google Kubernetes Engine（GKE）クラスタの登録

* Astra Control Service にプライベート GKE クラスタを追加できますか。 *

はい。 Astra Control Service にプライベート GKE クラスタを追加できます。プライベートGKEクラスタを作成するには https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Project_Astra/How_to_create_a_private_GKE_cluster_to_work_with_project_Astra["この技術情報アーティクルの手順に従ってください"^]。

プライベートクラスタにはが必要です https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept["許可されたネットワーク"^] Astra Control の IP アドレスを許可するように設定します。

52.188.218.166-32

* GKE クラスタは共有 VPC 上に存在できますか。 *

はい、 Astra Control は共有 VPC 内のクラスタを管理できます。 link:set-up-google-cloud.html["VPC の共有構成を行うための Astra サービスアカウントの設定方法について説明します"]。

* サービスアカウントの資格情報はどこにありますか？ *

にログインしたら https://console.cloud.google.com/["Google Cloud Console の略"^]のサービスアカウントの詳細は、「 * IAM と管理」セクションに記載されています。詳細については、を参照してください link:set-up-google-cloud.html["Astra Control 向け Google Cloud のセットアップ方法"]。

* 異なる GCP プロジェクトから異なる GKE クラスタを追加します。これは Astra Control でサポートされていますか。 *

いいえ。これはサポートされている構成ではありません。1 つの GCP プロジェクトのみがサポートされます。

endif::gcp[]



== クラスタの削除

* 適切な登録解除、クラスタの停止、関連付けられたボリュームの削除を行うにはどうすればよいですか *

. link:../use/unmanage.html["Astra Control からアプリケーションの管理を解除"]。
. link:../use/unmanage.html#stop-managing-compute["Astra Control からクラスタの登録を解除します"]。
. link:../use/unmanage.html#deleting-clusters-from-your-cloud-provider["永続ボリューム要求を削除します"]。
. クラスタを削除


* Astra Control からクラスタを削除した後、アプリケーションとデータはどうなりますか。 *

Astra Control からクラスタを削除しても、クラスタの構成（アプリケーションと永続的ストレージ）は変更されません。このクラスタで作成されたアプリケーションの Snapshot やバックアップを Astra Control で復元することはできません。ストレージバックエンドに格納されているボリューム Snapshot データは削除されません。Astra Control で作成した永続的ストレージのバックアップは、クラウドプロバイダのオブジェクトストアに残りますが、リストアには使用できません。

ifdef::gcp[]


WARNING: GCP から削除する場合は、必ず事前に Astra Control からクラスタを削除してください。GCP からクラスターを削除しても、 Astra Control で管理されている間は、原因の問題が Astra Control アカウントで発生する可能性があります。

endif::gcp[]

* Astra Trident は、 Astra Control からクラスタを削除したときにアンインストールされますか。 *

Astra Tridentは、Astra Controlからクラスタを削除してもクラスタからアンインストールされません。



== アプリケーションの管理

* Astra Control はアプリケーションを導入できますか。 *

Astra Control はアプリケーションを導入しない。アプリケーションは Astra Control の外部に導入する必要があります。

* ネットアップ以外のストレージにあるアプリケーションは Astra Control で管理できますか。 *

いいえネットアップ以外のストレージを使用しているアプリケーションは Astra Control で検出できますが、ネットアップ以外のストレージを使用しているアプリケーションは管理できません。

ifdef::gcp[]

* アプリケーションの PVC が GCP CVS にバインドされていません。何が間違っていますか？ *

Astra Trident オペレータは、 Astra Control に正常に追加された後、デフォルトのストレージクラスを「 NetApp-cvs-perf-premium 」に設定します。アプリケーションの PVC が Cloud Volumes Service for Google Cloud にバインドされていない場合は、次の手順を実行します。

* kubectl get sc を実行し ' デフォルトのストレージ・クラスをチェックします
* アプリケーションの導入に使用した YAML ファイルまたは Helm チャートをチェックし、別のストレージクラスが定義されているかどうかを確認します。
* ワーカーノードのイメージタイプが Ubuntu であり、 NFS マウントが成功していることを確認します。


endif::gcp[]

* アプリケーションを Astra Control から管理しなくなった後、どうなりますか。 *

既存のバックアップまたは Snapshot がすべて削除されます。アプリケーションとデータは引き続き使用できます。管理対象外のアプリケーション、またはそのアプリケーションに属するバックアップや Snapshot では、データ管理操作を実行できません。



== データ管理の操作

* Astra Control では、オブジェクトストアバケットはどこに作成されますか？ *

オブジェクトストアの場所は、最初に管理されたクラスタの格納場所で決まります。たとえば、最初に追加したクラスタがヨーロッパゾーンにある場合、バケットはその同じ地域に作成されます。必要に応じて、を実行できます link:../use/manage-buckets.html["バケットを追加します"]。

* 作成していないスナップショットがアカウントにあります。彼らはどこから来たのですか。 *

一部の状況では、 Astra Control は、別のプロセスを実行する際にスナップショットを自動的に作成します。これらの Snapshot が数分以上前のものであれば、安全に削除できます。

* アプリケーションは複数の PVS を使用しています。Astra Control は、これらすべての PVC のスナップショットとバックアップを作成しますか。 *

はい。Astra Control によるアプリケーションのスナップショット操作には、アプリケーションの PVC にバインドされているすべての PVS のスナップショットが含まれます。

* Astra Control で取得したスナップショットをクラウドプロバイダから直接管理できますか。 *

いいえAstra Control で作成したスナップショットとバックアップは、 Astra Control でのみ管理できます。
