---
sidebar: sidebar 
permalink: get-started/manage-private-cluster.html 
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster 
summary: 環境のセットアップが完了したら、 Kubernetes クラスタを作成し、 Astra Control Service に追加することができます。 
---
= Astra Control Serviceを使用してプライベートクラスタを管理
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Service を使用すると、プライベート AKS クラスタを管理できます。以下の手順では、プライベートAKSクラスタをすでに作成し、リモートアクセスするためのセキュアな方法を準備していることを前提としています。プライベートAKSクラスタの作成とアクセスの詳細については、を参照してください https://docs.microsoft.com/azure/aks/private-clusters["Azure に関するドキュメント"^]。

* <<Astra Connectorオペレータを設置します>>
* <<永続的ストレージをセットアップする>>
* <<プライベートクラスタをAstra Control Serviceに追加します>>




== Astra Connectorオペレータを設置します

AKSのプライベートクラスタにAstraコネクタオペレータをインストールする必要があります。要塞ホストを使用している場合は、要塞ホストのコマンドラインからこれらのコマンドを問題 で実行します。

.手順
. Astra ConnectorオペレータGitHubリポジトリのクローンを作成します。
+
[source, console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. 展開された演算子パッケージの最上位レベルにディレクトリを変更して'straconnector _operator.yaml'ファイルを'ls'コマンドで表示できるようにします
. Astra Connector オペレータのネームスペースを作成します。
+
[source, console]
----
kubectl create ns astra-connector-operator
----
. 「 astraaconnector _operator.yaml 」ファイルを演算子名前空間に適用します。
+
[source, console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. プライベートクラスタコンポーネントのネームスペースを作成します。
+
[source, console]
----
kubectl create ns astra-connector
----
. の手順に従って、Astra Control APIトークンを生成します https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html["Astra Automationのドキュメント"^]。
. 必要に応じて、Astra Connectorオペレータリポジトリのconfig/samplesディレクトリにある設定ファイルを変更します。
. Astra コネクタのカスタムリソース定義（ CRD ）を適用します。
+
[source, console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. アストラコネクタのステータスを確認します。
+
[source, console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
次のような出力が表示されます。

+
[source, console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----




== 永続的ストレージをセットアップする

クラスタに永続的ストレージを設定してください。Azure NetApp Files またはAzureで管理されるディスクを使用できます。Azureで次のオプションを設定する方法の詳細については、「はじめに」のドキュメントを参照してください。

* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-anf.html["Azure NetApp Files を使用して Microsoft Azure をセットアップする"]
* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html["Azure で管理されているディスクを使用して Microsoft Azure をセットアップする"]




== プライベートクラスタをAstra Control Serviceに追加します

AKSのプライベートクラスタをAstra制御サービスに追加できるようになりました。標準のワークフローに従って、Astra Control Serviceにクラスタを追加します。 https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html["Astra Control Service から Kubernetes クラスタの管理を開始します"]。
