---
sidebar: sidebar 
permalink: get-started/manage-private-cluster.html 
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster 
summary: 環境のセットアップが完了したら、 Kubernetes クラスタを作成し、 Astra Control Service に追加することができます。 
---
= Astra Control Serviceを使用してプライベートクラスタを管理
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Serviceを使用して、AKSでプライベートAzure Kubernetes Service（AKS）クラスタとRed Hat OpenShiftクラスタを管理できます。ここでは、プライベートAKSまたはOpenShiftクラスタがすでに作成されており、リモートからアクセスするための安全な方法が用意されていることを前提としています。プライベートAKSまたはOpenShiftクラスタの作成とアクセスの詳細については、次のドキュメントを参照してください。

* https://docs.microsoft.com/azure/aks/private-clusters["プライベートAKSクラスタに関するAzureのドキュメント"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["プライベートOpenShiftクラスタに関するAzureのドキュメント"^]


Astra Control Serviceを使用して、AKSでプライベートAzure Kubernetes Service（AKS）クラスタとプライベートRed Hat OpenShiftクラスタを管理できます。ここでは、プライベートAKSまたはOpenShiftクラスタがすでに作成されており、リモートからアクセスするための安全な方法が用意されていることを前提としています。プライベートAKSまたはOpenShiftクラスタの作成とアクセスの詳細については、次のドキュメントを参照してください。

* https://docs.microsoft.com/azure/aks/private-clusters["プライベートAKSクラスタに関するAzureのドキュメント"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["プライベートOpenShiftクラスタに関するAzureのドキュメント"^]


Astra Control Serviceを使用して、プライベートAmazon Elastic Kubernetes Service（EKS）クラスタを管理できます。ここで説明する手順では、プライベートEKSクラスタがすでに作成されており、リモートからアクセスするためのセキュアな方法が用意されていることを前提としています。プライベートEKSクラスタの作成とアクセスの詳細については、を参照してください https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html["Amazon EKSのドキュメント"^]。



== Astra Connectorオペレータを設置します

Astra Connectorオペレータはプライベートクラスタにインストールする必要があります。要塞ホストを使用している場合は、要塞ホストのコマンドラインからこれらのコマンドを問題 で実行します。

.手順
. Astra ConnectorオペレータGitHubリポジトリのクローンを作成します。
+
[source, console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. 展開された演算子パッケージの最上位レベルにディレクトリを変更して'straconnector _operator.yaml'ファイルを'ls'コマンドで表示できるようにします
. Astra Connector オペレータのネームスペースを作成します。
+
[source, console]
----
kubectl create ns astra-connector-operator
----
. 「 astraaconnector _operator.yaml 」ファイルを演算子名前空間に適用します。
+
[source, console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. プライベートクラスタコンポーネントのネームスペースを作成します。
+
[source, console]
----
kubectl create ns astra-connector
----
. の手順に従って、Astra Control APIトークンを生成します https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html["Astra Automationのドキュメント"^]。
. Astra Connectorオペレータリポジトリのconfig/samplesディレクトリにある構成ファイルの例を変更して、次のキーに対応する環境固有の値を追加します。
+
** `spec.natssync-client.cloud-bridge-url`
** `spec.astra.token`
** `spec.astra.clusterName`
** `spec.astra.accountId`
+
例：

+
[listing]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: https://<your.astra.control.service.url>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
  astra:
    token: <Astra Control API token>
    clusterName: <your-cluster-name>
    accountId: <Astra Control account id>
    acceptEULA: yes
----


. Astra コネクタのカスタムリソース定義（ CRD ）を適用します。
+
[source, console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. アストラコネクタのステータスを確認します。
+
[source, console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
次のような出力が表示されます。

+
[source, console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----




== 永続的ストレージをセットアップする

クラスタに永続的ストレージを設定してください。永続的ストレージの設定の詳細については、『Get Started』ドキュメントを参照してください。



== プライベートクラスタをAstra Control Serviceに追加します

プライベートクラスタをAstra Control Serviceに追加できるようになりました。標準のワークフローに従って、Astra Control Serviceにクラスタを追加します。 https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html["Astra Control Service から Kubernetes クラスタの管理を開始します"]。
