---
sidebar: sidebar 
permalink: get-started/register.html 
keywords: BlueXP, sign up, log in, login, register, register for BlueXP, create account, sign up for account, get an account, account, accounts 
summary: Astra Controlサービスは、NetApp BlueXPの認証サービスに統合されています。BlueXPに登録すると、Astra Control Serviceやネットアップのその他のクラウドサービスにアクセスできます。 
---
= Astra Control Service アカウントに登録します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Controlサービスを使用するには、NetApp BlueXPアカウントに関連付けられたAstra Controlサービスアカウントが必要です。Astra Control Serviceの登録プロセスを完了し、BlueXPアカウントがない場合はBlueXPに登録してAstra Control Serviceにアクセスします。



== Astra Control アカウントに登録します

Astra Control Service にログインする前に、 Astra Control Service アカウントを取得する登録プロセスを完了する必要があります。

Astra Control Service を使用すると、アカウント内からアプリケーションを管理できます。アカウントには、アカウント内のアプリを表示および管理できるユーザーと、課金情報が含まれます。

.手順
. https://cloud.netapp.com/astra["BlueXPのAstra Controlページにアクセス"^]。
. [Get started now]*を選択します。
. 必要な情報をフォームに入力します。
+
フォームに入力する際に注意すべき重要事項は次のとおりです。

+
** グローバル貿易コンプライアンスの要件を満たすことが確認されるため、お客様の事業名と住所は正確である必要があります。
** 「 * Astra Account Name * 」は、御社の Astra Control Service アカウントの名前です。この名前は、 Astra Control Service のユーザーインタフェースに表示されます。必要に応じて、追加のアカウントを作成できます（最大 5 つ）。
** NetApp BlueXPアカウントをお持ちの場合は、[お勤め先のEメールアドレス]フィールドにそのアカウントに使用するEメールアドレスを入力します。NetApp BlueXPアカウントをまだお持ちでない場合は、ここに入力したEメールアドレスを使用してBlueXPにサインアップしてください。


. 「 * アカウントの作成 * 」を選択します。




== BlueXPにサインアップします

Astra Controlサービスは、NetApp BlueXPの認証サービスに統合されています。NetApp BlueXPには、BlueXPまたはNetApp Support Siteのクレデンシャルを使用してログインできます。NetApp BlueXPまたはNetApp Support Siteアカウントをまだお持ちでない場合は、BlueXPに登録してAstra Controlサービスやネットアップのその他のクラウドサービスにアクセスしてください。BlueXPまたはNetApp Support Siteのアカウントをすでにお持ちで、登録が完了している場合は、 https://astra.netapp.io["Astra 制御サービス"^] BlueXPまたはNetApp Support Siteのクレデンシャルを直接使用


TIP: シングルサインオンを使用して、社内ディレクトリのクレデンシャル（フェデレーテッドアイデンティティ）を使用してBlueXPにログインすることもできます。詳細については、を参照してください https://cloud.netapp.com/help-center["ヘルプセンター"^] 次に、 * Cloud Central サインインオプション * を選択します。

.手順
. に進みます https://cloud.netapp.com["NetApp BlueXP"^]。
. 右上の* Get Started *を選択します。
. 「サインアップ」を選択します。
. フォームに入力します。
+
ここに入力する電話番号とEメールアドレスが、前のAstra Control登録フォームで使用したものと同じであることを確認します。

. 「サインアップ」を選択します。
+

TIP: これらのフォームに入力するEメールアドレスは、NetApp BlueXPのユーザID用です。このBlueXPユーザIDは、新しいAstra Controlアカウントにサインアップするとき、またはAstra Control管理者から既存のAstra Controlアカウントへの招待を受けたときに使用します。

. NetApp BlueXPからEメールが届きます。電子メールは saas.support@netapp.com の住所から来、着くまで数分かかるかもしれない。スパムフォルダを確認してください。
. E メールが届いたら、 E メール内のリンクを選択して E メールアドレスを確認します。


.結果
これで、BlueXPの有効なユーザログインが確立されました。

登録が完了したら、BlueXPクレデンシャルを使用してAstra Controlに直接アクセスできます。 https://astra.netapp.io[]。
