---
sidebar: sidebar 
permalink: get-started/supported-deployments.html 
keywords: gke, aks, google kubernetes engine, azure kubernetes service 
summary: Astra Control Serviceを使用すると、クラウドプロバイダ環境の管理対象のKubernetesクラスタで実行されているアプリケーションを管理できます。 
---
= サポートされる Kubernetes 環境
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Serviceでは、Amazon Elastic Kubernetes Service（EKS）内の管理対象Kubernetesクラスタで実行されているアプリケーションのほか、ユーザが独自に管理するクラスタを管理できます。

Astra Control Serviceを使用すると、Google Kubernetes Engine（GKE）の管理対象Kubernetesクラスタで実行されているアプリだけでなく、独自に管理するクラスターも管理できます。

Astra Control Serviceを使用すると、Azure Kubernetes Service（AKS）の管理対象のKubernetesクラスタで実行されているアプリケーションだけでなく、独自に管理するクラスタも管理できます。

ifdef::aws[]

* link:set-up-amazon-web-services.html["Amazon Web Services for Astra Control Serviceのセットアップ方法について説明します"]。


endif::aws[]

ifdef::gcp[]

* link:set-up-google-cloud.html["Astra Control Service 向け Google Cloud のセットアップ方法をご確認ください"]。


endif::gcp[]

ifdef::azure[]

* link:set-up-microsoft-azure-with-anf.html["Azure NetApp Files for Astra Control サービスを使用した Microsoft Azure のセットアップ方法について説明します"]。
* link:set-up-microsoft-azure-with-amd.html["Azure で管理される Azure ディスクで Astra Control サービスを利用するための Microsoft Azure のセットアップ方法について説明します"]。


endif::azure[]

* link:add-first-cluster.html["Astra Control Serviceに追加する前に自己管理クラスタを準備する方法について説明します"]。

