---
sidebar: sidebar 
permalink: get-started/videos.html 
keywords: videos, Astra Control Service videos 
summary: このドキュメントサイトの多くのページには、 Astra Control サービスを使用してタスクを完了する方法を説明するビデオが含まれています。ビデオに関心がある場合は、この 1 ページにあるすべてのビデオを収集することで簡単になりました（プレイリストのように）。 
---
= Astra Control サービスのビデオ
:hardbreaks:
:icons: font
:imagesdir: ../media/


このドキュメントサイトの多くのページには、 Astra Control サービスのタスクを完了する方法を説明するビデオが含まれています。ビデオに関心がある場合は、この 1 ページのすべてのビデオを収集することで、簡単に操作できます（プレイリストのように）。



== Google Cloud のセットアップに関するビデオです

次のビデオでは、 GCP で実行されている Kubernetes クラスタを検出する前に、 Google Cloud で設定要件を満たす方法を説明します。



=== APIs を有効にします

特定の Google Cloud API にアクセスするには、プロジェクトに権限が必要です。次のビデオでは、 Google Cloud コンソールから API を有効にする方法を紹介します。 link:set-up-google-cloud.html#enable-apis-in-your-project["API の有効化の詳細をご覧ください"]。

video::get-started/video-enable-gcp-apis.mp4[width=848,height=480]


=== サービスアカウントを作成します

Astra Control Service は、 Google Cloud サービスアカウントを使用して、 Kubernetes アプリケーションデータ管理をお客様に代わって容易にします。次のビデオは、 Google Cloud コンソールからサービスアカウントを作成する方法を示しています。 link:set-up-google-cloud.html#create-a-service-account["サービスアカウントの作成の詳細については、こちらをご覧ください"]。

video::get-started/video-create-gcp-service-account.mp4[width=848,height=480]


=== サービスアカウントキーを作成します

Astra Control Service は、サービスアカウントキーを使用して、設定したサービスアカウントの ID を確立します。次のビデオは、 Google Cloud コンソールからサービスアカウントキーを作成する方法を示しています。 link:set-up-google-cloud.html#create-a-service-account-key-2["サービスアカウントキーの作成の詳細については、こちらをご覧ください"]。

video::get-started/video-create-gcp-service-account-key.mp4[width=848,height=480]


== Astra Control の使用に関するビデオ

次のビデオでは、 Astra Control を使用して一般的なタスクを実行する方法を紹介します。



=== Astra Control からクラスタを管理

Astra Control サービスにログインしたら、まず Kubernetes コンピューティングを追加します。 link:add-first-cluster.html["クラスタの管理に関する詳細情報"]。

video::get-started/video-manage-cluster.mp4[width=848,height=480]


=== 保護ポリシーを設定します

保護ポリシーは、定義されたスケジュールでスナップショット、バックアップ、またはその両方を作成することでアプリケーションを保護します。Snapshot とバックアップを毎時、日次、週次、および月単位で作成し、保持するコピーの数を指定できます。 link:../use/protect-apps.html["保護ポリシーの設定の詳細については、こちらをご覧ください"]。

video::use/video-set-protection-policy.mp4[width=848,height=480]