---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: 既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。 
---
= 既知の問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。

現在のリリースに影響する既知の問題は次のとおりです。

.アプリケーション
*  clones fail after an application is deployed with a set storage class
*  page loads forever when trying to restore an application belonging to a deleted cluster
*  to define an app on a namespace that has been deleted and recreated


.バックアップ、リストア、およびクローニング
*  of an app results in PV size larger than original PV
*  clones fail using a specific version of PostgreSQL
*  backups and snapshots fail if the volumesnapshotclass is added after a cluster is managed


ifdef::azure[]

*  backup buckets use LRS redundancy by default


endif::azure[]

.その他の問題
*  eventually begin to fail when using external-snapshotter version 4.2.0
*  data management operations fail with Internal Service Error (500) when Astra Trident is offline




== ストレージクラスを設定してアプリケーションを導入すると、アプリケーションのクローンが失敗する

ストレージクラスを明示的に設定してアプリケーションをデプロイした後 ( たとえば、「 helm install...-set global.storageClass=NetApp-cvs-perf-extreme 」 ) 、アプリケーションのクローンを作成しようとすると、ターゲットクラスタに最初に指定されたストレージクラスが必要になります。ストレージクラスを明示的に設定したアプリケーションを、同じストレージクラスを含まないクラスタにクローニングすると、失敗します。このシナリオではリカバリ手順はありません。



== 削除されたクラスタに属するアプリケーションをリストアしようとすると、アプリケーションページが無期限にロードされます

アプリケーションページから削除されたクラスタからアプリケーションを復元しようとしても、アプリケーションページの読み込みは完了しません。回避策 として、アプリケーションリストページのアプリケーションのアクションメニューからアプリケーションを復元します。



== 削除および再作成されたネームスペースにアプリケーションを定義できません

ネームスペースを使用してアプリケーションを定義し、ネームスペースを削除してから、同じネームスペースにアプリケーションを再インストールすると、409エラーコードで処理が失敗します。再作成した名前空間を使用してアプリケーションを定義するには、最初に古いアプリケーションインスタンスを削除します。



== アプリケーションをリストアすると、 PV のサイズが元の PV よりも大きくなります

バックアップの作成後に永続ボリュームのサイズを変更し、そのバックアップからリストアすると、永続ボリュームのサイズはバックアップのサイズではなく PV の新しいサイズと一致します。



== 特定のバージョンの PostgreSQL を使用すると、アプリケーションクローンが失敗します

Bitnami PostgreSQL 11.5.0 チャートを使用すると、同じクラスタ内のアプリケーションクローンは一貫して失敗します。正常にクローニングするには、以前のバージョンのグラフを使用してください。



== クラスタの管理後にボリュームnapshotclassを追加すると、アプリケーションのバックアップとSnapshotが失敗します

このシナリオでは、UI 500エラーでバックアップとSnapshotが失敗します。回避策 として、アプリリストを更新します。

ifdef::azure[]



== Azureバックアップバケットでは、デフォルトでLRS冗長性が使用されます

デフォルトでは、バケットAstra Control ServiceはAzure Kubernetes Serviceのバックアップを保存するためにを使用し、ローカルのRedundant Storage（LRS）冗長性オプションを使用します。Azureバケットで永続性を高めた冗長性オプションを使用する場合は、Azureクラウドプロバイダのセットアップ手順のオプションの手順を参照してください。

* link:../get-started/set-up-microsoft-azure-with-amd.html["Azure で管理されているディスクを使用して Microsoft Azure をセットアップする"]
* link:../get-started/set-up-microsoft-azure-with-anf.html["Azure NetApp Files を使用して Microsoft Azure をセットアップする"]


endif::azure[]



== 外部スナップショットバージョン 4.2.0 を使用している場合、スナップショットは最終的に失敗します

Kubernetes 1.20 または 1.21 で Kubernetes snapshot-controller （別名 external-snapshotter ）バージョン 4.2.0 を使用すると、 Snapshot が失敗することがあります。これを防ぐには、別のを使用してください https://kubernetes-csi.github.io/docs/snapshot-controller.html["サポートされているバージョン"^] バージョン 4.2.1 などの外部 Snapshot データ。 Kubernetes バージョン 1.20 または 1.21 で使用。



== Astra Trident がオフラインの場合、 Internal Service Error （ 500 ）によりアプリケーションデータ管理処理が失敗する

アプリケーションクラスタの Astra Trident がオフラインになり（オンラインに戻った）、 500 件の内部サービスエラーが発生した場合に、アプリケーションデータ管理を試みると、アプリケーションクラスタ内のすべての Kubernetes ノードを再起動して機能を復旧します。
