---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: 既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。 
---
= 既知の問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。

現在のリリースに影響する既知の問題は次のとおりです。

.アプリケーション
* <<削除および再作成されたネームスペースにアプリケーションを定義できません>>


.バックアップ、リストア、およびクローニング
* <<特定のバージョンの PostgreSQL を使用すると、アプリケーションクローンが失敗します>>
* <<クラスタの管理後にボリュームnapshotclassを追加すると、アプリケーションのバックアップとSnapshotが失敗します>>


.その他の問題
* <<Astra Trident がオフラインの場合、 Internal Service Error （ 500 ）によりアプリケーションデータ管理処理が失敗する>>




== 削除および再作成されたネームスペースにアプリケーションを定義できません

ネームスペースを使用してアプリケーションを定義し、ネームスペースを削除してから、同じネームスペースにアプリケーションを再インストールすると、409エラーコードで処理が失敗します。再作成した名前空間を使用してアプリケーションを定義するには、最初に古いアプリケーションインスタンスを削除します。



== 特定のバージョンの PostgreSQL を使用すると、アプリケーションクローンが失敗します

Bitnami PostgreSQL 11.5.0 チャートを使用すると、同じクラスタ内のアプリケーションクローンは一貫して失敗します。正常にクローニングするには、以前のバージョンのグラフを使用してください。



== クラスタの管理後にボリュームnapshotclassを追加すると、アプリケーションのバックアップとSnapshotが失敗します

このシナリオでは、UI 500エラーでバックアップとSnapshotが失敗します。回避策 として、アプリリストを更新します。



== Astra Trident がオフラインの場合、 Internal Service Error （ 500 ）によりアプリケーションデータ管理処理が失敗する

アプリケーションクラスタの Astra Trident がオフラインになり（オンラインに戻った）、 500 件の内部サービスエラーが発生した場合に、アプリケーションデータ管理を試みると、アプリケーションクラスタ内のすべての Kubernetes ノードを再起動して機能を復旧します。
