---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: limitations, known limitations, interoperability 
summary: 既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください 
---
= 既知の制限
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください



== 一般的な制限事項

以下の制限事項は、サポートされている Kubernetes 環境での Astra Control Service による Kubernetes クラスタの管理に影響します。



=== 正常でないポッドは、アプリケーション管理に影響を与えます

管理対象アプリケーションにポッドが正常な状態でない場合、 Astra Control Service は新しいバックアップとクローンを作成できません。



=== Astra Trident はクラスタからアンインストールされません

Astra Control Service からクラスタの管理を解除しても、 Astra Trident はクラスタから自動的にアンインストールされません。Astra Trident をアンインストールするには、が必要です https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Astra Trident のドキュメントで次の手順を実行します"^]。



=== Postgres ポッドへの既存の接続が原因で障害が発生します

Postgres ポッドで操作を実行する場合は、 psql コマンドを使用するためにポッド内で直接接続しないでください。Astra Control Service では、 psql にアクセスしてデータベースをフリーズしたり、解凍したりする必要があります。既存の接続がある場合、スナップショット、バックアップ、またはクローンは失敗します。



== GKE クラスタの管理に関する制限事項

Google Kubernetes Engine （ GKE ）での Kubernetes クラスタの管理には、次の制限事項があります。



=== 1 つの GCP プロジェクトと 1 つのサービスアカウントがサポートされます

Astra Control Service は、 1 つの Google Cloud Platform プロジェクトと 1 つのサービスアカウントをサポートします。Astra Control Service には複数のサービスアカウントを追加しないでください。また、サービスアカウントの資格情報をローテーションすることはできません。



=== Google Marketplace アプリは検証されていません

Google Marketplace から導入されたアプリは、ネットアップでは検証していません。一部のユーザから、 Google Marketplace から導入された Postgres 、 MariaDB 、 MySQL アプリケーションの検出やバックアップで問題が報告されることがあります。

Astra Control Service で使用するアプリケーションの種類に関係なく、必ず自分でバックアップとリストアのワークフローをテストして、ディザスタリカバリの要件を満たすことを確認してください。



=== 永続的ボリュームの制限

Google Cloud のリージョンごとに最大 100 個のボリュームを使用できます。この制限に達すると、新しいクローンまたはボリュームの作成が失敗します。 link:../support/get-help.html["ボリューム数の上限を引き上げるには、サポートにお問い合わせください"]。



== アプリケーション管理の制限

Astra Control Service によるアプリケーションの管理には、次の制限があります。



=== 参照渡し演算子を使用してインストールされたアプリケーションのクローンが失敗することがあります

Astra Control は、名前空間を対象とした演算子でインストールされたアプリケーションをサポートします。これらの演算子は、一般に「パスバイリファレンス」アーキテクチャではなく「パスバイ値」で設計されています。これらのパターンに続くいくつかのオペレータアプリを次に示します。

* https://github.com/k8ssandra/cass-operator/tree/v1.7.1["Apache K8ssandra"^]
* https://github.com/jenkinsci/kubernetes-operator["Jenkins CI"^]
* https://github.com/percona/percona-xtradb-cluster-operator["Percona XtraDB クラスタ"^]


Astra Control では、「パスバイリファレンス」アーキテクチャ（ CockroachDB オペレータなど）で設計されたオペレータをクローニングできない場合があります。クローニング処理では、クローニング処理の一環として独自の新しいシークレットが存在する場合でも、クローニングされたオペレータがソースオペレータから Kubernetes シークレットを参照しようとします。Astra Control がソースオペレータの Kubernetes シークレットを認識しないため、クローニング処理が失敗する場合があります。
